let PARTIDOS = [
    [11600, 'XXXXX', 'Vélez Sarsfield', 'Deportivo Español'],
    [11930, 'XXXXX', 'Instituto', 'Dep. Riestra'],
    [11700, 'XXXXX', 'Novorizontino', 'Guaraní'],
    [11700, 'XXXXX', 'Sampaio Correa', 'Londrina'],
    [11700, 'XXXXX', 'Sport Recife', 'Avaí'],
    [11930, 'XXXXX', 'CRB', 'Mirassol'],
    [10500, 'XXXXX', 'Gwangju', 'Suwon Bluewings'],
    [10500, 'XXXXX', 'Jeonbuk', 'Daegu'],
    [10530, 'XXXXX', 'Gangwon', 'Daejeon'],
    [10530, 'XXXXX', 'Incheon', 'Seoul'],
    [11900, 'XXXXX', 'Imbabura', 'Vargas Torres'],
    [11900, 'XXXXX', 'Macará', 'América de Quito'],
    [11400, 'XXXXX', 'Levante', 'Albacete'],
    [12130, 'XXXXX', 'Los Angeles FC', 'Atlanta Utd'],
    [11830, 'XXXXX', 'Charleston', 'Detroit'],
    [11900, 'XXXXX', 'Birmingham', 'Inter Miami'],
    [12030, 'XXXXX', 'Real Salt Lake', 'Los Angeles Galaxy'],
    [11400, 'XXXXX', 'Fiorentina', 'West Ham'],
    [10430, 'XXXXX', 'Hiroshima', 'FC Tokushima'],
    [10430, 'XXXXX', 'Verdy', 'Kusatsu'],
    [10500, 'XXXXX', 'Albirex Niigata', 'Reilac Shiga'],
    [10500, 'XXXXX', 'Avispa Fukuoka', 'Imabari'],
    [10500, 'XXXXX', 'Blaublitz', 'Tochigi'],
    [10500, 'XXXXX', 'C-Osaka', 'Cento Cuore Harima'],
    [10500, 'XXXXX', 'Chiba', 'Omiya Ardija'],
    [10500, 'XXXXX', 'G-Osaka', 'Kochi United'],
    [10500, 'XXXXX', 'Iwata', 'Kamatamare'],
    [10500, 'XXXXX', 'Kanazawa', 'Machida'],
    [10500, 'XXXXX', 'Kashima', 'Honda FC'],
    [10500, 'XXXXX', 'Kashiwa', 'Yamanashi Gakuin'],
    [10500, 'XXXXX', 'Kawasaki', 'Tochigi City'],
    [10500, 'XXXXX', 'Kyoto', 'Toyama'],
    [10500, 'XXXXX', 'Mito', 'Renofa Yamaguchi'],
    [10500, 'XXXXX', 'Nagoya', 'Veertien Mie'],
    [10500, 'XXXXX', 'Oita', 'Verspah Oita'],
    [10500, 'XXXXX', 'Okayama', 'Kitakyushu'],
    [10500, 'XXXXX', 'Sagan Tosu', 'Tegevajaro Miyazaki'],
    [10500, 'XXXXX', 'Sapporo', 'Sagamihara'],
    [10500, 'XXXXX', 'Shimizu', 'Gifu'],
    [10500, 'XXXXX', 'Shonan', 'BTOP Hokkaido'],
    [10500, 'XXXXX', 'Tokushima', 'Iwaki'],
    [10500, 'XXXXX', 'Tokyo', 'Fukushima Utd'],
    [10500, 'XXXXX', 'Urawa', 'Kansai'],
    [10500, 'XXXXX', 'V-Varen Nagasaki', 'Kofu'],
    [10500, 'XXXXX', 'Vegalta Sendai', 'Fujieda MYFC'],
    [10500, 'XXXXX', 'Yamagata', 'Sony Sendai'],
    [10500, 'XXXXX', 'Yokohama M.', 'Urayasu'],
    [12100, 'XXXXX', 'México', 'Guatemala'],
    [10700, 'XXXXX', 'Japón Sub-21', 'Marruecos Sub-21'],
    [11030, 'XXXXX', 'Costa de Marfil Sub-21', 'Panamá Sub-21'],
    [10700, 'XXXXX', 'Yenisey', 'F. Voronezh'],
    [11000, 'XXXXX', 'Rodina Moscow', 'Nizhny Novgorod'],
    [11700, 'XXXXX', 'Argentinos Jrs. (Arg)', 'Liverpool M. (Uru)'],
    [11700, 'XXXXX', 'Ind. del Valle (Ecu)', 'Corinthians (Bra)'],
    [11700, 'XXXXX', 'Nacional (Uru)', 'Internacional (Bra)'],
    [11900, 'XXXXX', 'Aucas (Ecu)', 'Ñublense (Chi)'],
    [11930, 'XXXXX', 'Palmeiras (Bra)', 'Barcelona SC (Ecu)'],
    [11930, 'XXXXX', 'River Plate (Arg)', 'Fluminense (Bra)'],
    [12100, 'XXXXX', 'The Strongest (Bol)', 'Sporting Cristal (Per)'],
    [11900, 'XXXXX', 'Blooming (Bol)', 'Audax (Chi)'],
    [11900, 'XXXXX', 'Estudiantes L.P. (Arg)', 'Bragantino (Bra)'],
    [12100, 'XXXXX', 'Emelec (Ecu)', 'Guaraní (Par)'],
    [11200, 'XXXXX', 'Ankaragucu', 'Adana Demirspor'],
    [11200, 'XXXXX', 'Beşiktaş', 'Konyaspor'],
    [11200, 'XXXXX', 'Giresunspor', 'Antalyaspor'],
    [11200, 'XXXXX', 'Istanbulspor', 'Umraniyespor'],
]