let PARTIDOS_OPTIMIZADOS = [
    {
        "hora": 11030,
        "liga": "YE-POLE",
        "local": "Korona Kielce",
        "visitante": "Gornik Zabrze",
        "cuotaLocal": 2.55,
        "empate": 3.2,
        "cuotaVisitante": 2.75,
        "cantidadDeApuestas": 3,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 10800,
        "liga": "FRA2",
        "local": "Rodez Aveyron",
        "visitante": "Saint Etienne",
        "cuotaLocal": 3.3,
        "empate": 3.4,
        "cuotaVisitante": 2.1,
        "cantidadDeApuestas": 89,
        "cuotaCualquiera": 1.363
    },
    {
        "hora": 11200,
        "liga": "FRA2",
        "local": "Grenoble",
        "visitante": "Paris FC",
        "cuotaLocal": 2.75,
        "empate": 3,
        "cuotaVisitante": 2.65,
        "cantidadDeApuestas": 89,
        "cuotaCualquiera": 1.45
    },
    {
        "hora": 11200,
        "liga": "FRA2",
        "local": "EA Guingamp",
        "visitante": "Dunkerque",
        "cuotaLocal": 1.85,
        "empate": 3.4,
        "cuotaVisitante": 4.2,
        "cantidadDeApuestas": 90,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 11200,
        "liga": "FRA2",
        "local": "Troyes",
        "visitante": "Laval",
        "cuotaLocal": 1.95,
        "empate": 3.3,
        "cuotaVisitante": 3.9,
        "cantidadDeApuestas": 90,
        "cuotaCualquiera": 1.444
    },
    {
        "hora": 11200,
        "liga": "FRA2",
        "local": "AJ Auxerre",
        "visitante": "SC Amiens",
        "cuotaLocal": 1.9,
        "empate": 3.4,
        "cuotaVisitante": 4,
        "cantidadDeApuestas": 90,
        "cuotaCualquiera": 1.4
    },
    {
        "hora": 11200,
        "liga": "FRA2",
        "local": "Angers SCO",
        "visitante": "Sochaux",
        "cuotaLocal": 2.05,
        "empate": 3.3,
        "cuotaVisitante": 3.6,
        "cantidadDeApuestas": 90,
        "cuotaCualquiera": 1.48
    },
    {
        "hora": 11200,
        "liga": "FRA2",
        "local": "SC Bastia",
        "visitante": "Valenciennes",
        "cuotaLocal": 1.95,
        "empate": 3.25,
        "cuotaVisitante": 4,
        "cantidadDeApuestas": 88,
        "cuotaCualquiera": 1.45
    },
    {
        "hora": 11100,
        "liga": "YE-SUI1",
        "local": "FC Stade Ls Ouchy",
        "visitante": "FC Zurich",
        "cuotaLocal": 3.7,
        "empate": 3.6,
        "cuotaVisitante": 1.909,
        "cantidadDeApuestas": 90,
        "cuotaCualquiera": 1.3
    },
    {
        "hora": 11330,
        "liga": "YE-SUI1",
        "local": "Servette FC",
        "visitante": "FC St. Gallen",
        "cuotaLocal": 2.25,
        "empate": 3.4,
        "cuotaVisitante": 3,
        "cantidadDeApuestas": 90,
        "cuotaCualquiera": 1.25
    },
    {
        "hora": 11610,
        "liga": "ZA-COL1",
        "local": "Independiente Santa Fe",
        "visitante": "La Equidad",
        "cuotaLocal": 2,
        "empate": 3.4,
        "cuotaVisitante": 3.8,
        "cantidadDeApuestas": 155,
        "cuotaCualquiera": 1.45
    },
    {
        "hora": 11820,
        "liga": "ZA-COL1",
        "local": "CD Junior",
        "visitante": "Deportivo Pasto",
        "cuotaLocal": 1.769,
        "empate": 3.55,
        "cuotaVisitante": 4.5,
        "cantidadDeApuestas": 154,
        "cuotaCualquiera": 1.48
    },
    {
        "hora": 12030,
        "liga": "ZA-COL1",
        "local": "Once Caldas",
        "visitante": "Deportivo Pereira",
        "cuotaLocal": 2,
        "empate": 3.4,
        "cuotaVisitante": 3.8,
        "cantidadDeApuestas": 155,
        "cuotaCualquiera": 1.45
    },
    {
        "hora": 12005,
        "liga": "ZA-MEX2",
        "local": "Dorados",
        "visitante": "Cancun FC",
        "cuotaLocal": 2.9,
        "empate": 3.35,
        "cuotaVisitante": 2.35,
        "cantidadDeApuestas": 87,
        "cuotaCualquiera": 1.4
    },
    {
        "hora": 12205,
        "liga": "ZA-MEX2",
        "local": "CD Tepatitlan de Morelos",
        "visitante": "Leones Negros",
        "cuotaLocal": 2.4,
        "empate": 3.3,
        "cuotaVisitante": 2.85,
        "cantidadDeApuestas": 88,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 10200,
        "liga": "MUJ",
        "local": "Australia (F)",
        "visitante": "Francia (F)",
        "cuotaLocal": 3.5,
        "empate": 3.25,
        "cuotaVisitante": 2.15,
        "cantidadDeApuestas": 190,
        "cuotaCualquiera": 1.5
    },
    {
        "hora": 10530,
        "liga": "MUJ",
        "local": "Inglaterra (F)",
        "visitante": "Colombia (F)",
        "cuotaLocal": 1.533,
        "empate": 3.75,
        "cuotaVisitante": 7.5,
        "cantidadDeApuestas": 188,
        "cuotaCualquiera": 1.55
    },
    {
        "hora": 11400,
        "liga": "ZA-BOL1",
        "local": "Always Ready",
        "visitante": "CA Nacional Potosi",
        "cuotaLocal": 1.85,
        "empate": 3.55,
        "cuotaVisitante": 3.6,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.3
    },
    {
        "hora": 11600,
        "liga": "ZA-BOL1",
        "local": "Club Aurora",
        "visitante": "Bolivar",
        "cuotaLocal": 2.55,
        "empate": 3.4,
        "cuotaVisitante": 2.4,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.363
    },
    {
        "hora": 11900,
        "liga": "ZA-BOL1",
        "local": "Oriente Petrolero",
        "visitante": "Real Tomayapo",
        "cuotaLocal": 1.75,
        "empate": 3.55,
        "cuotaVisitante": 4,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.38
    },
    {
        "hora": 11330,
        "liga": "ZA-BRA2",
        "local": "Criciuma SC",
        "visitante": "Londrina PR",
        "cuotaLocal": 1.65,
        "empate": 3.65,
        "cuotaVisitante": 5.5,
        "cantidadDeApuestas": 98,
        "cuotaCualquiera": 1.533
    },
    {
        "hora": 11500,
        "liga": "ZA-BRA2",
        "local": "Sampaio Correa MA",
        "visitante": "CRB Maceio AL",
        "cuotaLocal": 2.25,
        "empate": 3.1,
        "cuotaVisitante": 3.25,
        "cantidadDeApuestas": 100,
        "cuotaCualquiera": 1.55
    },
    {
        "hora": 11500,
        "liga": "ZA-BRA2",
        "local": "Botafogo SP",
        "visitante": "Ponte Preta SP",
        "cuotaLocal": 2.15,
        "empate": 3.1,
        "cuotaVisitante": 3.5,
        "cantidadDeApuestas": 98,
        "cuotaCualquiera": 1.65
    },
    {
        "hora": 11600,
        "liga": "ZA-BRA2",
        "local": "Vila Nova FC",
        "visitante": "Avai SC",
        "cuotaLocal": 1.727,
        "empate": 3.5,
        "cuotaVisitante": 5,
        "cantidadDeApuestas": 84,
        "cuotaCualquiera": 1.55
    },
    {
        "hora": 11400,
        "liga": "ZA-CHI1",
        "local": "Coquimbo",
        "visitante": "Colo Colo",
        "cuotaLocal": 3.3,
        "empate": 3.2,
        "cuotaVisitante": 2.1,
        "cantidadDeApuestas": 82,
        "cuotaCualquiera": 1.444
    },
    {
        "hora": 11630,
        "liga": "ZA-CHI1",
        "local": "OHiggins",
        "visitante": "Deportes Copiapo",
        "cuotaLocal": 2.05,
        "empate": 3.3,
        "cuotaVisitante": 3.35,
        "cantidadDeApuestas": 77,
        "cuotaCualquiera": 1.4
    },
    {
        "hora": 11300,
        "liga": "ZA-ECU1",
        "local": "Deportivo Cuenca",
        "visitante": "Libertad (Ecu)",
        "cuotaLocal": 1.769,
        "empate": 3.55,
        "cuotaVisitante": 4.2,
        "cantidadDeApuestas": 82,
        "cuotaCualquiera": 1.38
    },
    {
        "hora": 11530,
        "liga": "ZA-ECU1",
        "local": "Tecnico Universitario",
        "visitante": "El Nacional",
        "cuotaLocal": 2.4,
        "empate": 3.25,
        "cuotaVisitante": 2.75,
        "cantidadDeApuestas": 82,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 11800,
        "liga": "ZA-ECU1",
        "local": "Delfin",
        "visitante": "Barcelona SC",
        "cuotaLocal": 2.95,
        "empate": 3.25,
        "cuotaVisitante": 2.25,
        "cantidadDeApuestas": 81,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 11600,
        "liga": "ZA-PAR1",
        "local": "Resistencia",
        "visitante": "Libertad Asuncion",
        "cuotaLocal": 6,
        "empate": 4.333,
        "cuotaVisitante": 1.444,
        "cantidadDeApuestas": 76,
        "cuotaCualquiera": 1.3
    },
    {
        "hora": 11830,
        "liga": "ZA-PAR1",
        "local": "Guairena FC",
        "visitante": "Guarani Asuncion",
        "cuotaLocal": 3,
        "empate": 3.25,
        "cuotaVisitante": 2.2,
        "cantidadDeApuestas": 76,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 11515,
        "liga": "ZA-PER1",
        "local": "Club Sportivo Cienciano",
        "visitante": "Academia Cantolao",
        "cuotaLocal": 1.285,
        "empate": 5,
        "cuotaVisitante": 9,
        "cantidadDeApuestas": 80,
        "cuotaCualquiera": 1.285
    },
    {
        "hora": 11515,
        "liga": "ZA-PER1",
        "local": "Sport Boys Association",
        "visitante": "Asociacion Deportiva Tarma",
        "cuotaLocal": 2.3,
        "empate": 3.25,
        "cuotaVisitante": 2.85,
        "cantidadDeApuestas": 82,
        "cuotaCualquiera": 1.45
    },
    {
        "hora": 11900,
        "liga": "ZA-PER1",
        "local": "Universitario de Deportes",
        "visitante": "EM Deportivo Binacional",
        "cuotaLocal": 1.111,
        "empate": 7,
        "cuotaVisitante": 21,
        "cantidadDeApuestas": 76,
        "cuotaCualquiera": 1
    },
    {
        "hora": 11430,
        "liga": "ZA-VEN1",
        "local": "Rayo Zuliano",
        "visitante": "Metropolitano SC",
        "cuotaLocal": 2.65,
        "empate": 3.1,
        "cuotaVisitante": 2.5,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 11710,
        "liga": "ZA-VEN1",
        "local": "Caracas FC",
        "visitante": "Zamora FC",
        "cuotaLocal": 1.533,
        "empate": 3.7,
        "cuotaVisitante": 5.5,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.4
    },
    {
        "hora": 11945,
        "liga": "ZA-VEN1",
        "local": "Monagas SC",
        "visitante": "Carabobo FC",
        "cuotaLocal": 2.6,
        "empate": 3,
        "cuotaVisitante": 2.6,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.48
    },
    {
        "hora": 10900,
        "liga": "YE-BEL1",
        "local": "RWD Molenbeek",
        "visitante": "Mechelen",
        "cuotaLocal": 2.3,
        "empate": 3.6,
        "cuotaVisitante": 2.95,
        "cantidadDeApuestas": 100,
        "cuotaCualquiera": 1.3
    },
    {
        "hora": 11115,
        "liga": "YE-BEL1",
        "local": "St. Gilloise",
        "visitante": "OH Leuven",
        "cuotaLocal": 1.45,
        "empate": 4.75,
        "cuotaVisitante": 6.5,
        "cantidadDeApuestas": 99,
        "cuotaCualquiera": 1.25
    },
    {
        "hora": 11000,
        "liga": "YE-BIE1",
        "local": "FC Gomel",
        "visitante": "Naftan Novopolotsk",
        "cuotaLocal": 1.6,
        "empate": 3.7,
        "cuotaVisitante": 5,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1
    },
    {
        "hora": 11200,
        "liga": "YE-BIE1",
        "local": "Dinamo Brest",
        "visitante": "Isloch",
        "cuotaLocal": 2.55,
        "empate": 3.5,
        "cuotaVisitante": 2.4,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.333
    },
    {
        "hora": 10930,
        "liga": "YE-HOL1",
        "local": "PSV Eindhoven",
        "visitante": "Utrecht",
        "cuotaLocal": 1.363,
        "empate": 5.25,
        "cuotaVisitante": 8.5,
        "cantidadDeApuestas": 189,
        "cuotaCualquiera": 1.25
    },
    {
        "hora": 11145,
        "liga": "YE-HOL1",
        "local": "Heerenveen",
        "visitante": "RKC Waalwijk",
        "cuotaLocal": 1.75,
        "empate": 4,
        "cuotaVisitante": 4.2,
        "cantidadDeApuestas": 174,
        "cuotaCualquiera": 1.285
    },
    {
        "hora": 11300,
        "liga": "YE-HOL1",
        "local": "Ajax Amsterdam",
        "visitante": "Heracles Almelo",
        "cuotaLocal": 1.181,
        "empate": 8,
        "cuotaVisitante": 15,
        "cantidadDeApuestas": 176,
        "cuotaCualquiera": 1.181
    },
    {
        "hora": 11400,
        "liga": "YE-HOL1",
        "local": "Zwolle",
        "visitante": "Sparta Rotterdam",
        "cuotaLocal": 2.55,
        "empate": 3.5,
        "cuotaVisitante": 2.8,
        "cantidadDeApuestas": 175,
        "cuotaCualquiera": 1.35
    },
    {
        "hora": 10930,
        "liga": "YE-POR1",
        "local": "Gil Vicente",
        "visitante": "Portimonense SC",
        "cuotaLocal": 2.05,
        "empate": 3.45,
        "cuotaVisitante": 3.8,
        "cantidadDeApuestas": 173,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 11200,
        "liga": "YE-POR1",
        "local": "Sporting Farense",
        "visitante": "Casa Pia Atletico",
        "cuotaLocal": 2.5,
        "empate": 3.2,
        "cuotaVisitante": 3.1,
        "cantidadDeApuestas": 171,
        "cuotaCualquiera": 1.5
    },
    {
        "hora": 11430,
        "liga": "YE-POR1",
        "local": "Sporting De Lisboa",
        "visitante": "FC Vizela",
        "cuotaLocal": 1.181,
        "empate": 7.5,
        "cuotaVisitante": 19,
        "cantidadDeApuestas": 173,
        "cuotaCualquiera": 1.25
    },
    {
        "hora": 11030,
        "liga": "YE-RUM1",
        "local": "FC Otelul Galati",
        "visitante": "Universitatea Cluj",
        "cuotaLocal": 3.1,
        "empate": 3,
        "cuotaVisitante": 2.3,
        "cantidadDeApuestas": 75,
        "cuotaCualquiera": 1.571
    },
    {
        "hora": 11330,
        "liga": "YE-RUM1",
        "local": "CS Municipal Studentesc Iasi",
        "visitante": "CS U Craiova",
        "cuotaLocal": 3.7,
        "empate": 3.3,
        "cuotaVisitante": 1.95,
        "cantidadDeApuestas": 81,
        "cuotaCualquiera": 1.48
    },
    {
        "hora": 10700,
        "liga": "YE-RUS1",
        "local": "Lokomotiv Moscow",
        "visitante": "Krylia Sovetov Samara",
        "cuotaLocal": 2.05,
        "empate": 3.6,
        "cuotaVisitante": 3.1,
        "cantidadDeApuestas": 83,
        "cuotaCualquiera": 1.3
    },
    {
        "hora": 10930,
        "liga": "YE-RUS1",
        "local": "FK Gazovik Orenburg",
        "visitante": "Krasnodar",
        "cuotaLocal": 2.875,
        "empate": 3.45,
        "cuotaVisitante": 2.2,
        "cantidadDeApuestas": 84,
        "cuotaCualquiera": 1.25
    },
    {
        "hora": 11200,
        "liga": "YE-RUS1",
        "local": "Rostov",
        "visitante": "Rubin Kazan",
        "cuotaLocal": 2.2,
        "empate": 3.1,
        "cuotaVisitante": 3.2,
        "cantidadDeApuestas": 83,
        "cuotaCualquiera": 1.45
    },
    {
        "hora": 11115,
        "liga": "YE-TUR1",
        "local": "Kasimpasa",
        "visitante": "Ankaragucu",
        "cuotaLocal": 2.3,
        "empate": 3.5,
        "cuotaVisitante": 2.85,
        "cantidadDeApuestas": 110,
        "cuotaCualquiera": 1.3
    },
    {
        "hora": 11115,
        "liga": "YE-TUR1",
        "local": "Konyaspor",
        "visitante": "Istanbulspor AS",
        "cuotaLocal": 1.833,
        "empate": 3.65,
        "cuotaVisitante": 4,
        "cantidadDeApuestas": 111,
        "cuotaCualquiera": 1.333
    },
    {
        "hora": 11345,
        "liga": "YE-TUR1",
        "local": "Kayserispor",
        "visitante": "Galatasaray",
        "cuotaLocal": 5.25,
        "empate": 4,
        "cuotaVisitante": 1.571,
        "cantidadDeApuestas": 104,
        "cuotaCualquiera": 1.285
    },
    {
        "hora": 11345,
        "liga": "YE-TUR1",
        "local": "Pendikspor",
        "visitante": "Hatayspor",
        "cuotaLocal": 2.15,
        "empate": 3.5,
        "cuotaVisitante": 3.1,
        "cantidadDeApuestas": 111,
        "cuotaCualquiera": 1.333
    },
    {
        "hora": 10900,
        "liga": "YE-TUR2",
        "local": "Keciorengucu",
        "visitante": "Eyupspor",
        "cuotaLocal": 2.875,
        "empate": 3.1,
        "cuotaVisitante": 2.3,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 11000,
        "liga": "ESP1",
        "local": "Real Sociedad",
        "visitante": "Girona",
        "cuotaLocal": 1.615,
        "empate": 4,
        "cuotaVisitante": 5.5,
        "cantidadDeApuestas": 235,
        "cuotaCualquiera": 1.38
    },
    {
        "hora": 11230,
        "liga": "ESP1",
        "local": "Las Palmas",
        "visitante": "RCD Mallorca",
        "cuotaLocal": 2.5,
        "empate": 3.1,
        "cuotaVisitante": 3.2,
        "cantidadDeApuestas": 191,
        "cuotaCualquiera": 1.615
    },
    {
        "hora": 11430,
        "liga": "ESP1",
        "local": "Athletic Bilbao",
        "visitante": "Real Madrid",
        "cuotaLocal": 3.3,
        "empate": 3.55,
        "cuotaVisitante": 2.2,
        "cantidadDeApuestas": 263,
        "cuotaCualquiera": 1.363
    },
    {
        "hora": 11200,
        "liga": "ESP2",
        "local": "Racing Santander",
        "visitante": "SD Eibar",
        "cuotaLocal": 2.875,
        "empate": 3.1,
        "cuotaVisitante": 2.5,
        "cantidadDeApuestas": 101,
        "cuotaCualquiera": 1.533
    },
    {
        "hora": 11400,
        "liga": "ESP2",
        "local": "Real Zaragoza",
        "visitante": "CF Villarreal B",
        "cuotaLocal": 1.75,
        "empate": 3.4,
        "cuotaVisitante": 5,
        "cantidadDeApuestas": 85,
        "cuotaCualquiera": 1.5
    },
    {
        "hora": 11500,
        "liga": "ESP2",
        "local": "Elche",
        "visitante": "Ferrol",
        "cuotaLocal": 1.833,
        "empate": 3.45,
        "cuotaVisitante": 4.333,
        "cantidadDeApuestas": 89,
        "cuotaCualquiera": 1.45
    },
    {
        "hora": 11000,
        "liga": "FRA1",
        "local": "Marseille",
        "visitante": "Stade Reims",
        "cuotaLocal": 1.7,
        "empate": 4,
        "cuotaVisitante": 5,
        "cantidadDeApuestas": 187,
        "cuotaCualquiera": 1.333
    },
    {
        "hora": 11400,
        "liga": "FRA1",
        "local": "Paris S.G.",
        "visitante": "Lorient",
        "cuotaLocal": 1.333,
        "empate": 5.75,
        "cuotaVisitante": 9,
        "cantidadDeApuestas": 172,
        "cuotaCualquiera": 1.25
    },
    {
        "hora": 10630,
        "liga": "R-ING1",
        "local": "Arsenal",
        "visitante": "Nottingham Forest",
        "cuotaLocal": 1.181,
        "empate": 7.5,
        "cuotaVisitante": 15,
        "cantidadDeApuestas": 311,
        "cuotaCualquiera": 1.2
    },
    {
        "hora": 10900,
        "liga": "R-ING1",
        "local": "Bournemouth",
        "visitante": "West Ham United",
        "cuotaLocal": 2.7,
        "empate": 3.45,
        "cuotaVisitante": 2.6,
        "cantidadDeApuestas": 277,
        "cuotaCualquiera": 1.363
    },
    {
        "hora": 10900,
        "liga": "R-ING1",
        "local": "Brighton",
        "visitante": "Luton Town",
        "cuotaLocal": 1.333,
        "empate": 5.5,
        "cuotaVisitante": 9.5,
        "cantidadDeApuestas": 256,
        "cuotaCualquiera": 1.25
    },
    {
        "hora": 10900,
        "liga": "R-ING1",
        "local": "Everton",
        "visitante": "Fulham",
        "cuotaLocal": 2.25,
        "empate": 3.45,
        "cuotaVisitante": 3.25,
        "cantidadDeApuestas": 287,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 10900,
        "liga": "R-ING1",
        "local": "Sheffield United",
        "visitante": "Crystal Palace",
        "cuotaLocal": 3.1,
        "empate": 3.3,
        "cuotaVisitante": 2.45,
        "cantidadDeApuestas": 275,
        "cuotaCualquiera": 1.48
    },
    {
        "hora": 11130,
        "liga": "R-ING1",
        "local": "Newcastle",
        "visitante": "Aston Villa",
        "cuotaLocal": 1.769,
        "empate": 3.9,
        "cuotaVisitante": 4.5,
        "cantidadDeApuestas": 310,
        "cuotaCualquiera": 1.333
    },
    {
        "hora": 10600,
        "liga": "ALEC",
        "local": "FC Carl Zeiss Jena",
        "visitante": "Hertha Berlin",
        "cuotaLocal": 5.25,
        "empate": 4.2,
        "cuotaVisitante": 1.5,
        "cantidadDeApuestas": 77,
        "cuotaCualquiera": 1.25
    },
    {
        "hora": 10600,
        "liga": "ALEC",
        "local": "TSG Balingen",
        "visitante": "Stuttgart",
        "cuotaLocal": 31,
        "empate": 9.5,
        "cuotaVisitante": 1.04,
        "cantidadDeApuestas": 39,
        "cuotaCualquiera": 1.142
    },
    {
        "hora": 10830,
        "liga": "ALEC",
        "local": "Gutersloh",
        "visitante": "Holstein Kiel",
        "cuotaLocal": 29,
        "empate": 8.5,
        "cuotaVisitante": 1.071,
        "cantidadDeApuestas": 75,
        "cuotaCualquiera": 1.222
    },
    {
        "hora": 10830,
        "liga": "ALEC",
        "local": "FC Oberneuland",
        "visitante": "Nurnberg",
        "cuotaLocal": 26,
        "empate": 10,
        "cuotaVisitante": 1.04,
        "cantidadDeApuestas": 2,
        "cuotaCualquiera": 1
    },
    {
        "hora": 10830,
        "liga": "ALEC",
        "local": "FC Teutonia 05",
        "visitante": "Bayer Leverkusen",
        "cuotaLocal": 31,
        "empate": 11,
        "cuotaVisitante": 1.02,
        "cantidadDeApuestas": 38,
        "cuotaCualquiera": 1.111
    },
    {
        "hora": 10830,
        "liga": "ALEC",
        "local": "FC Viktoria Köln",
        "visitante": "Werder Bremen",
        "cuotaLocal": 5.75,
        "empate": 4.333,
        "cuotaVisitante": 1.444,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.25
    },
    {
        "hora": 11100,
        "liga": "ALEC",
        "local": "Arminia Bielefeld",
        "visitante": "VfL Bochum",
        "cuotaLocal": 4.2,
        "empate": 3.85,
        "cuotaVisitante": 1.7,
        "cantidadDeApuestas": 75,
        "cuotaCualquiera": 1.25
    },
    {
        "hora": 11100,
        "liga": "ALEC",
        "local": "SV Elversberg",
        "visitante": "Mainz 05",
        "cuotaLocal": 3.45,
        "empate": 3.65,
        "cuotaVisitante": 1.85,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.285
    },
    {
        "hora": 11100,
        "liga": "ALEC",
        "local": "Hallescher FC",
        "visitante": "Greuther Furth",
        "cuotaLocal": 4.333,
        "empate": 3.75,
        "cuotaVisitante": 1.65,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.3
    },
    {
        "hora": 11045,
        "liga": "ITAC",
        "local": "Empoli",
        "visitante": "Cittadella",
        "cuotaLocal": 1.6,
        "empate": 3.6,
        "cuotaVisitante": 5.25,
        "cantidadDeApuestas": 75,
        "cuotaCualquiera": 1.4
    },
    {
        "hora": 11100,
        "liga": "ITAC",
        "local": "Bari",
        "visitante": "Parma",
        "cuotaLocal": 2.375,
        "empate": 3.1,
        "cuotaVisitante": 2.85,
        "cantidadDeApuestas": 77,
        "cuotaCualquiera": 1.48
    },
    {
        "hora": 11400,
        "liga": "ITAC",
        "local": "Verona",
        "visitante": "Ascoli",
        "cuotaLocal": 1.533,
        "empate": 3.8,
        "cuotaVisitante": 5.75,
        "cantidadDeApuestas": 75,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 11415,
        "liga": "ITAC",
        "local": "Cagliari",
        "visitante": "Palermo",
        "cuotaLocal": 1.666,
        "empate": 3.65,
        "cuotaVisitante": 4.75,
        "cantidadDeApuestas": 75,
        "cuotaCualquiera": 1.38
    },
    {
        "hora": 11345,
        "liga": "ALES",
        "local": "Bayern Munich",
        "visitante": "RB Leipzig",
        "cuotaLocal": 1.571,
        "empate": 4.5,
        "cuotaVisitante": 5.25,
        "cantidadDeApuestas": 197,
        "cuotaCualquiera": 1.25
    },
    {
        "hora": 11900,
        "liga": "ZA-BRA1",
        "local": "Botafogo RJ",
        "visitante": "Internacional RS",
        "cuotaLocal": 2,
        "empate": 3.3,
        "cuotaVisitante": 3.95,
        "cantidadDeApuestas": 189,
        "cuotaCualquiera": 1.533
    },
    {
        "hora": 11400,
        "liga": "ZA-COL2",
        "local": "Real Soacha Cundinamarca",
        "visitante": "Real Cartagena",
        "cuotaLocal": 2.55,
        "empate": 3,
        "cuotaVisitante": 2.7,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.533
    },
    {
        "hora": 11500,
        "liga": "ZA-COL2",
        "local": "Fortaleza FC",
        "visitante": "Deportes Quindio",
        "cuotaLocal": 1.769,
        "empate": 3.4,
        "cuotaVisitante": 4.2,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.48
    },
    {
        "hora": 11530,
        "liga": "ZA-COL2",
        "local": "Cortulua",
        "visitante": "Tigres FC",
        "cuotaLocal": 1.95,
        "empate": 3.1,
        "cuotaVisitante": 3.65,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.533
    },
    {
        "hora": 11530,
        "liga": "ZA-COL2",
        "local": "Cucuta Deportivo",
        "visitante": "Barranquilla",
        "cuotaLocal": 1.363,
        "empate": 4.333,
        "cuotaVisitante": 7.5,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.35
    },
    {
        "hora": 11530,
        "liga": "ZA-COL2",
        "local": "Leones FC",
        "visitante": "Atletico de Cali",
        "cuotaLocal": 1.727,
        "empate": 3.5,
        "cuotaVisitante": 4.2,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.4
    },
    {
        "hora": 11800,
        "liga": "ZA-EST2",
        "local": "Miami FC",
        "visitante": "Indy Eleven",
        "cuotaLocal": 1.9,
        "empate": 3.35,
        "cuotaVisitante": 3.65,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.363
    },
    {
        "hora": 11800,
        "liga": "ZA-EST2",
        "local": "Pittsburgh Riverhounds",
        "visitante": "Hartford Athletic FC",
        "cuotaLocal": 1.363,
        "empate": 4.5,
        "cuotaVisitante": 6.5,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.285
    },
    {
        "hora": 11830,
        "liga": "ZA-EST2",
        "local": "Detroit City",
        "visitante": "Charleston Battery",
        "cuotaLocal": 2.55,
        "empate": 3.1,
        "cuotaVisitante": 2.6,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 11830,
        "liga": "ZA-EST2",
        "local": "Birmingham Legion FC",
        "visitante": "Sacramento Republic FC",
        "cuotaLocal": 2.45,
        "empate": 3.3,
        "cuotaVisitante": 2.55,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.38
    },
    {
        "hora": 11900,
        "liga": "ZA-EST2",
        "local": "Louisville City",
        "visitante": "Rio Grande Valley FC",
        "cuotaLocal": 1.8,
        "empate": 3.5,
        "cuotaVisitante": 3.95,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.363
    },
    {
        "hora": 12000,
        "liga": "ZA-EST2",
        "local": "New Mexico United",
        "visitante": "San Antonio",
        "cuotaLocal": 2.55,
        "empate": 3.25,
        "cuotaVisitante": 2.5,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.363
    },
    {
        "hora": 12100,
        "liga": "ZA-EST2",
        "local": "San Diego Loyal SC",
        "visitante": "Memphis 901 FC",
        "cuotaLocal": 1.85,
        "empate": 3.6,
        "cuotaVisitante": 3.55,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.333
    },
    {
        "hora": 12200,
        "liga": "ZA-EST2",
        "local": "Phoenix Rising FC",
        "visitante": "El Paso Locomotive FC",
        "cuotaLocal": 2,
        "empate": 3.55,
        "cuotaVisitante": 3.1,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.333
    },
    {
        "hora": 11300,
        "liga": "AMI-E",
        "local": "FK Partizani Tirana",
        "visitante": "Roma",
        "cuotaLocal": 7,
        "empate": 4.5,
        "cuotaVisitante": 1.35,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.285
    },
    {
        "hora": 11300,
        "liga": "AMI-E",
        "local": "Fiorentina",
        "visitante": "OFI Crete",
        "cuotaLocal": 1.48,
        "empate": 4.2,
        "cuotaVisitante": 5.5,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.3
    },
    {
        "hora": 11330,
        "liga": "AMI-E",
        "local": "Juventus",
        "visitante": "Atalanta",
        "cuotaLocal": 2.1,
        "empate": 3.65,
        "cuotaVisitante": 3.1,
        "cantidadDeApuestas": 90,
        "cuotaCualquiera": 1.333
    },
    {
        "hora": 10300,
        "liga": "AMI-C",
        "local": "Torrejon",
        "visitante": "Marchamalo",
        "cuotaLocal": 2,
        "empate": 3.25,
        "cuotaVisitante": 3.2,
        "cantidadDeApuestas": 9,
        "cuotaCualquiera": 1
    },
    {
        "hora": 10300,
        "liga": "AMI-C",
        "local": "Atletico Madrid B",
        "visitante": "CF Intercity",
        "cuotaLocal": 2.25,
        "empate": 3.2,
        "cuotaVisitante": 2.75,
        "cantidadDeApuestas": 9,
        "cuotaCualquiera": 1
    },
    {
        "hora": 10400,
        "liga": "AMI-C",
        "local": "Real Madrid B",
        "visitante": "Fuenlabrada",
        "cuotaLocal": 1.571,
        "empate": 3.7,
        "cuotaVisitante": 4.75,
        "cantidadDeApuestas": 9,
        "cuotaCualquiera": 1
    },
    {
        "hora": 10400,
        "liga": "AMI-C",
        "local": "UCAM Murcia",
        "visitante": "Granada B",
        "cuotaLocal": 2.05,
        "empate": 3.25,
        "cuotaVisitante": 3.1,
        "cantidadDeApuestas": 9,
        "cuotaCualquiera": 1
    },
    {
        "hora": 10900,
        "liga": "R-ESC1",
        "local": "Glasgow Rangers",
        "visitante": "Livingston",
        "cuotaLocal": 1.285,
        "empate": 5.75,
        "cuotaVisitante": 10,
        "cantidadDeApuestas": 112,
        "cuotaCualquiera": 1.222
    },
    {
        "hora": 10900,
        "liga": "R-ESC1",
        "local": "Ross County",
        "visitante": "St Johnstone",
        "cuotaLocal": 2.15,
        "empate": 3.25,
        "cuotaVisitante": 3.6,
        "cantidadDeApuestas": 112,
        "cuotaCualquiera": 1.48
    },
    {
        "hora": 10900,
        "liga": "R-ESC1",
        "local": "St Mirren",
        "visitante": "Dundee",
        "cuotaLocal": 2.1,
        "empate": 3.35,
        "cuotaVisitante": 3.6,
        "cantidadDeApuestas": 112,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 10900,
        "liga": "R-ESC2",
        "local": "Airdrieonians",
        "visitante": "Partick Thistle",
        "cuotaLocal": 2.9,
        "empate": 3.35,
        "cuotaVisitante": 2.2,
        "cantidadDeApuestas": 50,
        "cuotaCualquiera": 1.35
    },
    {
        "hora": 10900,
        "liga": "R-ESC2",
        "local": "Dundee United",
        "visitante": "Dunfermline",
        "cuotaLocal": 1.65,
        "empate": 3.7,
        "cuotaVisitante": 4.5,
        "cantidadDeApuestas": 50,
        "cuotaCualquiera": 1.363
    },
    {
        "hora": 10900,
        "liga": "R-ESC2",
        "local": "Ayr United",
        "visitante": "Inverness CT",
        "cuotaLocal": 2,
        "empate": 3.4,
        "cuotaVisitante": 3.35,
        "cantidadDeApuestas": 50,
        "cuotaCualquiera": 1.4
    },
    {
        "hora": 10900,
        "liga": "R-ESC2",
        "local": "Queens Park",
        "visitante": "Arbroath",
        "cuotaLocal": 1.7,
        "empate": 3.65,
        "cuotaVisitante": 4.2,
        "cantidadDeApuestas": 50,
        "cuotaCualquiera": 1.333
    },
    {
        "hora": 10900,
        "liga": "R-ESC2",
        "local": "Raith Rovers",
        "visitante": "Greenock Morton",
        "cuotaLocal": 2.4,
        "empate": 3.2,
        "cuotaVisitante": 2.7,
        "cantidadDeApuestas": 50,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 10630,
        "liga": "R-ING2",
        "local": "Coventry",
        "visitante": "Middlesbrough",
        "cuotaLocal": 2.45,
        "empate": 3.35,
        "cuotaVisitante": 3,
        "cantidadDeApuestas": 195,
        "cuotaCualquiera": 1.4
    },
    {
        "hora": 10900,
        "liga": "R-ING2",
        "local": "Birmingham City",
        "visitante": "Leeds United",
        "cuotaLocal": 3.25,
        "empate": 3.55,
        "cuotaVisitante": 2.2,
        "cantidadDeApuestas": 192,
        "cuotaCualquiera": 1.363
    },
    {
        "hora": 10900,
        "liga": "R-ING2",
        "local": "Cardiff City",
        "visitante": "QPR",
        "cuotaLocal": 1.909,
        "empate": 3.75,
        "cuotaVisitante": 4,
        "cantidadDeApuestas": 191,
        "cuotaCualquiera": 1.45
    },
    {
        "hora": 10900,
        "liga": "R-ING2",
        "local": "Huddersfield",
        "visitante": "Leicester City",
        "cuotaLocal": 4.5,
        "empate": 3.95,
        "cuotaVisitante": 1.75,
        "cantidadDeApuestas": 190,
        "cuotaCualquiera": 1.333
    },
    {
        "hora": 10900,
        "liga": "R-ING2",
        "local": "Hull City",
        "visitante": "Sheffield Wednesday",
        "cuotaLocal": 2.5,
        "empate": 3.3,
        "cuotaVisitante": 3,
        "cantidadDeApuestas": 191,
        "cuotaCualquiera": 1.4
    },
    {
        "hora": 10900,
        "liga": "R-ING2",
        "local": "Ipswich Town",
        "visitante": "Stoke City",
        "cuotaLocal": 2.15,
        "empate": 3.6,
        "cuotaVisitante": 3.4,
        "cantidadDeApuestas": 192,
        "cuotaCualquiera": 1.38
    },
    {
        "hora": 10900,
        "liga": "R-ING2",
        "local": "Millwall",
        "visitante": "Bristol City",
        "cuotaLocal": 1.9,
        "empate": 3.55,
        "cuotaVisitante": 4.333,
        "cantidadDeApuestas": 190,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 10900,
        "liga": "R-ING2",
        "local": "Preston",
        "visitante": "Sunderland",
        "cuotaLocal": 2.75,
        "empate": 3.4,
        "cuotaVisitante": 2.625,
        "cantidadDeApuestas": 193,
        "cuotaCualquiera": 1.4
    },
    {
        "hora": 10900,
        "liga": "R-ING2",
        "local": "Rotherham",
        "visitante": "Blackburn Rovers",
        "cuotaLocal": 2.95,
        "empate": 3.35,
        "cuotaVisitante": 2.45,
        "cantidadDeApuestas": 191,
        "cuotaCualquiera": 1.4
    },
    {
        "hora": 10900,
        "liga": "R-ING2",
        "local": "Southampton",
        "visitante": "Norwich City",
        "cuotaLocal": 1.85,
        "empate": 3.8,
        "cuotaVisitante": 4.2,
        "cantidadDeApuestas": 191,
        "cuotaCualquiera": 1.363
    },
    {
        "hora": 10900,
        "liga": "R-ING2",
        "local": "Watford",
        "visitante": "Plymouth Argyle",
        "cuotaLocal": 1.769,
        "empate": 3.9,
        "cuotaVisitante": 4.75,
        "cantidadDeApuestas": 190,
        "cuotaCualquiera": 1.363
    },
    {
        "hora": 10900,
        "liga": "R-ING2",
        "local": "West Bromwich",
        "visitante": "Swansea",
        "cuotaLocal": 2.1,
        "empate": 3.4,
        "cuotaVisitante": 3.65,
        "cantidadDeApuestas": 192,
        "cuotaCualquiera": 1.4
    },
    {
        "hora": 10900,
        "liga": "R-INGO",
        "local": "Bristol Rovers",
        "visitante": "Barnsley",
        "cuotaLocal": 3.2,
        "empate": 3.4,
        "cuotaVisitante": 2.25,
        "cantidadDeApuestas": 108,
        "cuotaCualquiera": 1.4
    },
    {
        "hora": 10900,
        "liga": "R-INGO",
        "local": "Burton Albion",
        "visitante": "Derby County",
        "cuotaLocal": 3.9,
        "empate": 3.7,
        "cuotaVisitante": 1.9,
        "cantidadDeApuestas": 110,
        "cuotaCualquiera": 1.4
    },
    {
        "hora": 10900,
        "liga": "R-INGO",
        "local": "Cheltenham Town",
        "visitante": "Bolton Wanderers",
        "cuotaLocal": 3.9,
        "empate": 3.5,
        "cuotaVisitante": 1.95,
        "cantidadDeApuestas": 110,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 10900,
        "liga": "R-INGO",
        "local": "Exeter City",
        "visitante": "Blackpool",
        "cuotaLocal": 2.8,
        "empate": 3.4,
        "cuotaVisitante": 2.5,
        "cantidadDeApuestas": 110,
        "cuotaCualquiera": 1.4
    },
    {
        "hora": 10900,
        "liga": "R-INGO",
        "local": "Fleetwood Town",
        "visitante": "Cambridge United",
        "cuotaLocal": 2.2,
        "empate": 3.4,
        "cuotaVisitante": 3.35,
        "cantidadDeApuestas": 110,
        "cuotaCualquiera": 1.444
    },
    {
        "hora": 10900,
        "liga": "R-INGO",
        "local": "Leyton Orient",
        "visitante": "Portsmouth",
        "cuotaLocal": 2.8,
        "empate": 3.35,
        "cuotaVisitante": 2.55,
        "cantidadDeApuestas": 109,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 10900,
        "liga": "R-INGO",
        "local": "Lincoln City",
        "visitante": "Wycombe Wanderers",
        "cuotaLocal": 2.5,
        "empate": 3.35,
        "cuotaVisitante": 2.85,
        "cantidadDeApuestas": 110,
        "cuotaCualquiera": 1.444
    },
    {
        "hora": 10900,
        "liga": "R-INGO",
        "local": "Oxford United",
        "visitante": "Carlisle",
        "cuotaLocal": 1.85,
        "empate": 3.7,
        "cuotaVisitante": 4,
        "cantidadDeApuestas": 111,
        "cuotaCualquiera": 1.38
    },
    {
        "hora": 10900,
        "liga": "R-INGO",
        "local": "Peterborough United",
        "visitante": "Charlton Athletic",
        "cuotaLocal": 1.95,
        "empate": 3.65,
        "cuotaVisitante": 3.7,
        "cantidadDeApuestas": 111,
        "cuotaCualquiera": 1.35
    },
    {
        "hora": 10900,
        "liga": "R-INGO",
        "local": "Port Vale",
        "visitante": "Reading",
        "cuotaLocal": 2.5,
        "empate": 3.4,
        "cuotaVisitante": 2.75,
        "cantidadDeApuestas": 109,
        "cuotaCualquiera": 1.38
    },
    {
        "hora": 10900,
        "liga": "R-INGO",
        "local": "Stevenage",
        "visitante": "Shrewsbury",
        "cuotaLocal": 2.15,
        "empate": 3.5,
        "cuotaVisitante": 3.4,
        "cantidadDeApuestas": 109,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 10900,
        "liga": "R-INGO",
        "local": "Wigan",
        "visitante": "Northampton",
        "cuotaLocal": 2.1,
        "empate": 3.55,
        "cuotaVisitante": 3.5,
        "cantidadDeApuestas": 109,
        "cuotaCualquiera": 1.38
    },
    {
        "hora": 10900,
        "liga": "R-INGT",
        "local": "AFC Wimbledon",
        "visitante": "Wrexham FC",
        "cuotaLocal": 3.45,
        "empate": 3.5,
        "cuotaVisitante": 2.1,
        "cantidadDeApuestas": 110,
        "cuotaCualquiera": 1.38
    },
    {
        "hora": 10900,
        "liga": "R-INGT",
        "local": "Barrow FC",
        "visitante": "Sutton United",
        "cuotaLocal": 2.45,
        "empate": 3.2,
        "cuotaVisitante": 3,
        "cantidadDeApuestas": 108,
        "cuotaCualquiera": 1.5
    },
    {
        "hora": 10900,
        "liga": "R-INGT",
        "local": "Bradford City",
        "visitante": "Colchester",
        "cuotaLocal": 1.95,
        "empate": 3.5,
        "cuotaVisitante": 4,
        "cantidadDeApuestas": 109,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 10900,
        "liga": "R-INGT",
        "local": "Gillingham",
        "visitante": "Accrington",
        "cuotaLocal": 2,
        "empate": 3.45,
        "cuotaVisitante": 3.8,
        "cantidadDeApuestas": 108,
        "cuotaCualquiera": 1.5
    },
    {
        "hora": 10900,
        "liga": "R-INGT",
        "local": "Harrogate Town",
        "visitante": "Forest Green Rovers",
        "cuotaLocal": 2.3,
        "empate": 3.4,
        "cuotaVisitante": 3.1,
        "cantidadDeApuestas": 109,
        "cuotaCualquiera": 1.4
    },
    {
        "hora": 10900,
        "liga": "R-INGT",
        "local": "Mansfield Town",
        "visitante": "Morecambe",
        "cuotaLocal": 1.55,
        "empate": 4.2,
        "cuotaVisitante": 6,
        "cantidadDeApuestas": 109,
        "cuotaCualquiera": 1.333
    },
    {
        "hora": 10900,
        "liga": "R-INGT",
        "local": "MK Dons",
        "visitante": "Tranmere",
        "cuotaLocal": 1.85,
        "empate": 3.6,
        "cuotaVisitante": 4.333,
        "cantidadDeApuestas": 111,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 10900,
        "liga": "R-INGT",
        "local": "Newport",
        "visitante": "Doncaster Rovers",
        "cuotaLocal": 2.2,
        "empate": 3.4,
        "cuotaVisitante": 3.25,
        "cantidadDeApuestas": 110,
        "cuotaCualquiera": 1.45
    },
    {
        "hora": 10900,
        "liga": "R-INGT",
        "local": "Notts County",
        "visitante": "Grimsby Town",
        "cuotaLocal": 1.7,
        "empate": 3.95,
        "cuotaVisitante": 4.75,
        "cantidadDeApuestas": 110,
        "cuotaCualquiera": 1.333
    },
    {
        "hora": 10900,
        "liga": "R-INGT",
        "local": "Salford City",
        "visitante": "Crawley Town",
        "cuotaLocal": 1.5,
        "empate": 4.333,
        "cuotaVisitante": 6.25,
        "cantidadDeApuestas": 109,
        "cuotaCualquiera": 1.333
    },
    {
        "hora": 10900,
        "liga": "R-INGT",
        "local": "Swindon Town",
        "visitante": "Crewe Alexandra",
        "cuotaLocal": 1.8,
        "empate": 3.75,
        "cuotaVisitante": 4.333,
        "cantidadDeApuestas": 111,
        "cuotaCualquiera": 1.38
    },
    {
        "hora": 10900,
        "liga": "R-INGT",
        "local": "Walsall",
        "visitante": "Stockport County",
        "cuotaLocal": 3.8,
        "empate": 3.35,
        "cuotaVisitante": 2.05,
        "cantidadDeApuestas": 108,
        "cuotaCualquiera": 1.533
    },
    {
        "hora": 10900,
        "liga": "R-INGN",
        "local": "AFC Fylde",
        "visitante": "Chesterfield",
        "cuotaLocal": 3.95,
        "empate": 3.65,
        "cuotaVisitante": 1.75,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.3
    },
    {
        "hora": 10900,
        "liga": "R-INGN",
        "local": "Boreham Wood",
        "visitante": "Halifax Town",
        "cuotaLocal": 2.15,
        "empate": 3.1,
        "cuotaVisitante": 3.25,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.533
    },
    {
        "hora": 10900,
        "liga": "R-INGN",
        "local": "Dorking Wanderers",
        "visitante": "Maidenhead United",
        "cuotaLocal": 2.05,
        "empate": 3.4,
        "cuotaVisitante": 3.1,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.333
    },
    {
        "hora": 10900,
        "liga": "R-INGN",
        "local": "Eastleigh FC",
        "visitante": "Wealdstone FC",
        "cuotaLocal": 1.666,
        "empate": 3.6,
        "cuotaVisitante": 4.333,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.363
    },
    {
        "hora": 10900,
        "liga": "R-INGN",
        "local": "Ebbsfleet United",
        "visitante": "Solihull Moors FC",
        "cuotaLocal": 2.05,
        "empate": 3.3,
        "cuotaVisitante": 3.25,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.363
    },
    {
        "hora": 10900,
        "liga": "R-INGN",
        "local": "Hartlepool",
        "visitante": "Gateshead FC",
        "cuotaLocal": 2.375,
        "empate": 3.35,
        "cuotaVisitante": 2.65,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.35
    },
    {
        "hora": 10900,
        "liga": "R-INGN",
        "local": "Oldham",
        "visitante": "Aldershot Town",
        "cuotaLocal": 1.95,
        "empate": 3.3,
        "cuotaVisitante": 3.5,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.38
    },
    {
        "hora": 10900,
        "liga": "R-INGN",
        "local": "Oxford City",
        "visitante": "Rochdale",
        "cuotaLocal": 3.1,
        "empate": 3.45,
        "cuotaVisitante": 2.05,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.35
    },
    {
        "hora": 10900,
        "liga": "R-INGN",
        "local": "Woking FC",
        "visitante": "Altrincham FC",
        "cuotaLocal": 1.6,
        "empate": 3.8,
        "cuotaVisitante": 4.75,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.35
    },
    {
        "hora": 10900,
        "liga": "R-INGN",
        "local": "York City",
        "visitante": "Kidderminster Harriers",
        "cuotaLocal": 1.95,
        "empate": 3.35,
        "cuotaVisitante": 3.45,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.4
    },
    {
        "hora": 10900,
        "liga": "R-INGN",
        "local": "Dagenham & Redbridge",
        "visitante": "Southend United",
        "cuotaLocal": 2.65,
        "empate": 3.1,
        "cuotaVisitante": 2.45,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 11130,
        "liga": "R-INGN",
        "local": "Bromley FC",
        "visitante": "Barnet",
        "cuotaLocal": 2.25,
        "empate": 3.4,
        "cuotaVisitante": 2.8,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.333
    },
    {
        "hora": 10500,
        "liga": "S-COR1",
        "local": "Jeonbuk Hyundai Motors",
        "visitante": "Suwon Samsung Bluewings",
        "cuotaLocal": 1.727,
        "empate": 3.65,
        "cuotaVisitante": 4.75,
        "cantidadDeApuestas": 94,
        "cuotaCualquiera": 1.4
    },
    {
        "hora": 10530,
        "liga": "S-COR1",
        "local": "Gangwon FC",
        "visitante": "Ulsan Hyundai Horang-I",
        "cuotaLocal": 4.5,
        "empate": 3.65,
        "cuotaVisitante": 1.75,
        "cantidadDeApuestas": 95,
        "cuotaCualquiera": 1.363
    },
    {
        "hora": 10600,
        "liga": "S-COR1",
        "local": "Jeju United",
        "visitante": "Suwon City FC",
        "cuotaLocal": 1.833,
        "empate": 3.7,
        "cuotaVisitante": 3.95,
        "cantidadDeApuestas": 97,
        "cuotaCualquiera": 1.3
    },
    {
        "hora": 10000,
        "liga": "S-JAP1",
        "local": "Consadole Sapporo",
        "visitante": "Sagan Tosu",
        "cuotaLocal": 1.727,
        "empate": 4,
        "cuotaVisitante": 4.2,
        "cantidadDeApuestas": 99,
        "cuotaCualquiera": 1.25
    },
    {
        "hora": 10400,
        "liga": "S-JAP1",
        "local": "Albirex Niigata",
        "visitante": "Shonan Bellmare",
        "cuotaLocal": 2.05,
        "empate": 3.4,
        "cuotaVisitante": 3.45,
        "cantidadDeApuestas": 97,
        "cuotaCualquiera": 1.38
    },
    {
        "hora": 10500,
        "liga": "S-JAP1",
        "local": "Avispa Fukuoka",
        "visitante": "Yokohama FC",
        "cuotaLocal": 1.85,
        "empate": 3.35,
        "cuotaVisitante": 4.333,
        "cantidadDeApuestas": 96,
        "cuotaCualquiera": 1.45
    },
    {
        "hora": 10500,
        "liga": "S-JAP1",
        "local": "Kawasaki Frontale",
        "visitante": "Vissel Kobe",
        "cuotaLocal": 2.15,
        "empate": 3.35,
        "cuotaVisitante": 3.3,
        "cantidadDeApuestas": 97,
        "cuotaCualquiera": 1.363
    },
    {
        "hora": 10500,
        "liga": "S-JAP1",
        "local": "FC Tokyo",
        "visitante": "Kyoto Sanga",
        "cuotaLocal": 2.05,
        "empate": 3.35,
        "cuotaVisitante": 3.6,
        "cantidadDeApuestas": 97,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 10500,
        "liga": "S-JAP1",
        "local": "Kashiwa Reysol",
        "visitante": "Cerezo Osaka",
        "cuotaLocal": 2.55,
        "empate": 3.2,
        "cuotaVisitante": 2.7,
        "cantidadDeApuestas": 97,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 10530,
        "liga": "S-JAP1",
        "local": "Yokohama F Marinos",
        "visitante": "Gamba Osaka",
        "cuotaLocal": 1.7,
        "empate": 4.2,
        "cuotaVisitante": 4.2,
        "cantidadDeApuestas": 99,
        "cuotaCualquiera": 1.222
    },
    {
        "hora": 10800,
        "liga": "YE-POLE",
        "local": "Stal Mielec",
        "visitante": "Slask Wroclaw",
        "cuotaLocal": 2.5,
        "empate": 3.25,
        "cuotaVisitante": 2.8,
        "cantidadDeApuestas": 96,
        "cuotaCualquiera": 1.45
    },
    {
        "hora": 11300,
        "liga": "YE-POLE",
        "local": "Widzew Lodz",
        "visitante": "LKS Lodz",
        "cuotaLocal": 1.95,
        "empate": 3.5,
        "cuotaVisitante": 3.75,
        "cantidadDeApuestas": 96,
        "cuotaCualquiera": 1.363
    },
    {
        "hora": 10500,
        "liga": "YE-POR2",
        "local": "Pacos Ferreira",
        "visitante": "Uniao Leiria",
        "cuotaLocal": 1.9,
        "empate": 3.55,
        "cuotaVisitante": 3.6,
        "cantidadDeApuestas": 76,
        "cuotaCualquiera": 1.35
    },
    {
        "hora": 10800,
        "liga": "YE-POR2",
        "local": "Nacional Madeira",
        "visitante": "Maritimo",
        "cuotaLocal": 2.75,
        "empate": 3.35,
        "cuotaVisitante": 2.35,
        "cantidadDeApuestas": 77,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 11200,
        "liga": "YE-POR2",
        "local": "Avs Futebol Sad",
        "visitante": "Cf Os Belenenses",
        "cuotaLocal": 1.769,
        "empate": 3.5,
        "cuotaVisitante": 4.2,
        "cantidadDeApuestas": 76,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 10800,
        "liga": "YE-REP1",
        "local": "FC Zlin",
        "visitante": "Slovan Liberec",
        "cuotaLocal": 2.5,
        "empate": 3.25,
        "cuotaVisitante": 2.6,
        "cantidadDeApuestas": 83,
        "cuotaCualquiera": 1.35
    },
    {
        "hora": 10800,
        "liga": "YE-REP1",
        "local": "Banik Ostrava",
        "visitante": "FC Hradec Kralove",
        "cuotaLocal": 1.833,
        "empate": 3.55,
        "cuotaVisitante": 3.85,
        "cantidadDeApuestas": 82,
        "cuotaCualquiera": 1.333
    },
    {
        "hora": 11100,
        "liga": "YE-REP1",
        "local": "FK Baumit Jablonec",
        "visitante": "AC Sparta Praha",
        "cuotaLocal": 4.75,
        "empate": 3.8,
        "cuotaVisitante": 1.615,
        "cantidadDeApuestas": 80,
        "cuotaCualquiera": 1.333
    },
    {
        "hora": 10700,
        "liga": "YE-UCR1",
        "local": "Chernomorets Odessa",
        "visitante": "Obolon Brovar Kiev",
        "cuotaLocal": 1.95,
        "empate": 3.3,
        "cuotaVisitante": 3.55,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.48
    },
    {
        "hora": 10900,
        "liga": "YE-UCR1",
        "local": "Kolos Kovalyovka",
        "visitante": "Veres Rivne",
        "cuotaLocal": 2.1,
        "empate": 3.2,
        "cuotaVisitante": 3.2,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.5
    },
    {
        "hora": 10900,
        "liga": "YE-UCR1",
        "local": "Polissya Zhytomyr",
        "visitante": "Rukh Vynnyky",
        "cuotaLocal": 2.15,
        "empate": 3.25,
        "cuotaVisitante": 3,
        "cantidadDeApuestas": 42,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 11900,
        "liga": "ZA-CHI1",
        "local": "Union Espanola",
        "visitante": "Huachipato",
        "cuotaLocal": 1,
        "empate": 1,
        "cuotaVisitante": 1,
        "cantidadDeApuestas": 1,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 11100,
        "liga": "YE-SUI1",
        "local": "FC Winterthur",
        "visitante": "Grasshoppers",
        "cuotaLocal": 1,
        "empate": 1,
        "cuotaVisitante": 1,
        "cantidadDeApuestas": 1,
        "cuotaCualquiera": 1.3
    },
    {
        "hora": 11345,
        "liga": "YE-TUR2",
        "local": "Kocaelispor",
        "visitante": "Manisa Futbol Kulubu",
        "cuotaLocal": 1,
        "empate": 1,
        "cuotaVisitante": 1,
        "cantidadDeApuestas": 1,
        "cuotaCualquiera": 1.4
    },
    {
        "hora": 11200,
        "liga": "FRA2",
        "local": "Caen",
        "visitante": "Pau FC",
        "cuotaLocal": 1,
        "empate": 1,
        "cuotaVisitante": 1,
        "cantidadDeApuestas": 1,
        "cuotaCualquiera": 1.42
    },
    {
        "hora": 11200,
        "liga": "FRA2",
        "local": "Quevilly US",
        "visitante": "Ajaccio",
        "cuotaLocal": 1,
        "empate": 1,
        "cuotaVisitante": 1,
        "cantidadDeApuestas": 1,
        "cuotaCualquiera": 1.55
    }
]
