let PARTIDOS_OPTIMIZADOS = [
    { "hora": 10500, "liga": "AMIE", "local": "Tottenham", "visitante": "West Ham United", "cuotaLocal": 2, "empate": 3.7, "cuotaVisitante": 3.5, "cantidadDeApuestas": 176 },
    { "hora": 10630, "liga": "AMIE", "local": "Bristol City", "visitante": "Swindon Town", "cuotaLocal": 1.533, "empate": 4.2, "cuotaVisitante": 5.25, "cantidadDeApuestas": 78 },
    { "hora": 11000, "liga": "AMIE", "local": "Génova", "visitante": "WSG Tirol", "cuotaLocal": 1.615, "empate": 3.9, "cuotaVisitante": 4.5, "cantidadDeApuestas": 76 },
    { "hora": 11100, "liga": "AMIE", "local": "Austria Wien", "visitante": "Aris Limassol", "cuotaLocal": 2.3, "empate": 3.65, "cuotaVisitante": 2.55, "cantidadDeApuestas": 42 },
    { "hora": 11200, "liga": "AMIE", "local": "Valencia", "visitante": "Nottingham Forest", "cuotaLocal": 2.3, "empate": 3.45, "cuotaVisitante": 2.875, "cantidadDeApuestas": 87 },
    { "hora": 11200, "liga": "AMIE", "local": "Real Oviedo", "visitante": "Racing Santander", "cuotaLocal": 2.3, "empate": 3.25, "cuotaVisitante": 2.875, "cantidadDeApuestas": 77 },
    { "hora": 11200, "liga": "AMIE", "local": "Sturm Graz", "visitante": "Galatasaray", "cuotaLocal": 2.75, "empate": 3.5, "cuotaVisitante": 2.25, "cantidadDeApuestas": 79 },
    { "hora": 11200, "liga": "AMIE", "local": "FC Penafiel", "visitante": "Desportivo Chaves", "cuotaLocal": 4, "empate": 3.4, "cuotaVisitante": 1.833, "cantidadDeApuestas": 77 },
    { "hora": 11200, "liga": "AMIE", "local": "Sevilla", "visitante": "AD Ceuta", "cuotaLocal": 1.125, "empate": 6.5, "cuotaVisitante": 17, "cantidadDeApuestas": 40 },
    { "hora": 11230, "liga": "AMIE", "local": "Osasuna", "visitante": "SD Huesca", "cuotaLocal": 1.571, "empate": 3.9, "cuotaVisitante": 5, "cantidadDeApuestas": 75 },
    { "hora": 11230, "liga": "AMIE", "local": "Altach", "visitante": "Villarreal", "cuotaLocal": 6.5, "empate": 4.75, "cuotaVisitante": 1.363, "cantidadDeApuestas": 75 },
    { "hora": 11300, "liga": "AMIE", "local": "Real Murcia", "visitante": "Sheffield Wednesday", "cuotaLocal": 4.2, "empate": 3.75, "cuotaVisitante": 1.7, "cantidadDeApuestas": 76 },
    { "hora": 11300, "liga": "AMIE", "local": "Panathinaikos", "visitante": "Rayo Vallecano", "cuotaLocal": 1.833, "empate": 3.45, "cuotaVisitante": 3.9, "cantidadDeApuestas": 77 },
    { "hora": 11300, "liga": "AMIE", "local": "Forest Green Rovers", "visitante": "Coventry", "cuotaLocal": 3.95, "empate": 3.65, "cuotaVisitante": 1.75, "cantidadDeApuestas": 42 },
    { "hora": 11300, "liga": "AMIE", "local": "FC Lisse", "visitante": "SC Telstar", "cuotaLocal": 5.25, "empate": 4.333, "cuotaVisitante": 1.45, "cantidadDeApuestas": 42 },
    { "hora": 11300, "liga": "AMIE", "local": "FC Rijnvogels", "visitante": "Koninklijke HFC", "cuotaLocal": 5.75, "empate": 4.75, "cuotaVisitante": 1.4, "cantidadDeApuestas": 42 },
    { "hora": 11330, "liga": "AMIE", "local": "Brackley Town", "visitante": "Burton Albion", "cuotaLocal": 7, "empate": 5.25, "cuotaVisitante": 1.3, "cantidadDeApuestas": 42 },
    { "hora": 11330, "liga": "AMIE", "local": "Southport FC", "visitante": "Morecambe", "cuotaLocal": 4.75, "empate": 3.9, "cuotaVisitante": 1.6, "cantidadDeApuestas": 42 },
    { "hora": 11330, "liga": "AMIE", "local": "Swindon Supermarine", "visitante": "Chippenham Town", "cuotaLocal": 2.45, "empate": 3.55, "cuotaVisitante": 2.45, "cantidadDeApuestas": 42 },
    { "hora": 11330, "liga": "AMIE", "local": "Gillingham", "visitante": "Charlton Athletic", "cuotaLocal": 3.1, "empate": 3.55, "cuotaVisitante": 2.05, "cantidadDeApuestas": 42 },
    { "hora": 11330, "liga": "AMIE", "local": "Hereford United", "visitante": "Swindon Town", "cuotaLocal": 2.6, "empate": 4, "cuotaVisitante": 2.15, "cantidadDeApuestas": 42 },
    { "hora": 11330, "liga": "AMIE", "local": "Stevenage", "visitante": "Colchester", "cuotaLocal": 1.95, "empate": 3.55, "cuotaVisitante": 3.3, "cantidadDeApuestas": 42 },
    { "hora": 11330, "liga": "AMIE", "local": "Torquay United", "visitante": "Plymouth Argyle", "cuotaLocal": 15, "empate": 8, "cuotaVisitante": 1.1, "cantidadDeApuestas": 41 },
    { "hora": 11345, "liga": "AMIE", "local": "Glasgow Rangers", "visitante": "Newcastle", "cuotaLocal": 3.9, "empate": 3.85, "cuotaVisitante": 1.8, "cantidadDeApuestas": 110 },
    { "hora": 11345, "liga": "AMIE", "local": "Cheltenham Town", "visitante": "West Bromwich", "cuotaLocal": 4.5, "empate": 4, "cuotaVisitante": 1.615, "cantidadDeApuestas": 77 },
    { "hora": 11345, "liga": "AMIE", "local": "Hull City", "visitante": "Barnsley", "cuotaLocal": 1.85, "empate": 3.5, "cuotaVisitante": 3.75, "cantidadDeApuestas": 77 },
    { "hora": 11345, "liga": "AMIE", "local": "AFC Fylde", "visitante": "Barrow FC", "cuotaLocal": 2.95, "empate": 3.65, "cuotaVisitante": 2.05, "cantidadDeApuestas": 42 },
    { "hora": 11345, "liga": "AMIE", "local": "Chester FC", "visitante": "Stockport County", "cuotaLocal": 5.75, "empate": 4.5, "cuotaVisitante": 1.42, "cantidadDeApuestas": 42 },
    { "hora": 11345, "liga": "AMIE", "local": "Sutton United", "visitante": "Millwall", "cuotaLocal": 4.2, "empate": 3.75, "cuotaVisitante": 1.7, "cantidadDeApuestas": 42 },
    { "hora": 11300, "liga": "R-ESCL", "local": "Huddersfield", "visitante": "Middlesbrough", "cuotaLocal": 2.9, "empate": 3.35, "cuotaVisitante": 2.35, "cantidadDeApuestas": 89 },
    { "hora": 11330, "liga": "R-ESCL", "local": "Mansfield Town", "visitante": "Grimsby Town", "cuotaLocal": 1.909, "empate": 3.35, "cuotaVisitante": 3.7, "cantidadDeApuestas": 77 },
    { "hora": 11330, "liga": "R-ESCL", "local": "Peterborough United", "visitante": "Swindon Town", "cuotaLocal": 1.615, "empate": 3.9, "cuotaVisitante": 4.75, "cantidadDeApuestas": 76 },
    { "hora": 11330, "liga": "R-ESCL", "local": "Swansea", "visitante": "Northampton", "cuotaLocal": 1.55, "empate": 3.95, "cuotaVisitante": 5.25, "cantidadDeApuestas": 75 },
    { "hora": 11345, "liga": "R-ESCL", "local": "Derby County", "visitante": "Blackpool", "cuotaLocal": 2.15, "empate": 3.45, "cuotaVisitante": 3.1, "cantidadDeApuestas": 3 },
    { "hora": 11345, "liga": "R-ESCL", "local": "Millwall", "visitante": "Reading", "cuotaLocal": 1.533, "empate": 4, "cuotaVisitante": 6, "cantidadDeApuestas": 86 },
    { "hora": 11345, "liga": "R-ESCL", "local": "Forest Green Rovers", "visitante": "Portsmouth", "cuotaLocal": 3.4, "empate": 3.5, "cuotaVisitante": 2.05, "cantidadDeApuestas": 89 },
    { "hora": 11345, "liga": "R-ESCL", "local": "QPR", "visitante": "Norwich City", "cuotaLocal": 2.75, "empate": 3.45, "cuotaVisitante": 2.45, "cantidadDeApuestas": 88 },
    { "hora": 11345, "liga": "R-ESCL", "local": "Stoke City", "visitante": "West Bromwich", "cuotaLocal": 2.5, "empate": 3.2, "cuotaVisitante": 2.8, "cantidadDeApuestas": 89 },
    { "hora": 11345, "liga": "R-ESCL", "local": "Accrington", "visitante": "Bradford City", "cuotaLocal": 2.625, "empate": 3.25, "cuotaVisitante": 2.5, "cantidadDeApuestas": 76 },
    { "hora": 11345, "liga": "R-ESCL", "local": "Barnsley", "visitante": "Tranmere", "cuotaLocal": 1.615, "empate": 3.9, "cuotaVisitante": 4.5, "cantidadDeApuestas": 76 },
    { "hora": 11345, "liga": "R-ESCL", "local": "Blackburn Rovers", "visitante": "Walsall", "cuotaLocal": 1.5, "empate": 4.2, "cuotaVisitante": 5.25, "cantidadDeApuestas": 76 },
    { "hora": 11345, "liga": "R-ESCL", "local": "Bolton Wanderers", "visitante": "Barrow FC", "cuotaLocal": 1.65, "empate": 3.9, "cuotaVisitante": 4.5, "cantidadDeApuestas": 76 },
    { "hora": 11345, "liga": "R-ESCL", "local": "Cheltenham Town", "visitante": "Birmingham City", "cuotaLocal": 2.8, "empate": 3.35, "cuotaVisitante": 2.3, "cantidadDeApuestas": 77 },
    { "hora": 11345, "liga": "R-ESCL", "local": "Plymouth Argyle", "visitante": "Leyton Orient", "cuotaLocal": 1.7, "empate": 3.7, "cuotaVisitante": 4.333, "cantidadDeApuestas": 75 },
    { "hora": 11345, "liga": "R-ESCL", "local": "Exeter City", "visitante": "Crawley Town", "cuotaLocal": 1.571, "empate": 3.9, "cuotaVisitante": 5, "cantidadDeApuestas": 74 },
    { "hora": 11345, "liga": "R-ESCL", "local": "MK Dons", "visitante": "Wycombe Wanderers", "cuotaLocal": 3.2, "empate": 3.25, "cuotaVisitante": 2.15, "cantidadDeApuestas": 78 },
    { "hora": 11345, "liga": "R-ESCL", "local": "Gillingham", "visitante": "Southampton", "cuotaLocal": 4.75, "empate": 3.85, "cuotaVisitante": 1.615, "cantidadDeApuestas": 74 },
    { "hora": 11345, "liga": "R-ESCL", "local": "Hull City", "visitante": "Doncaster Rovers", "cuotaLocal": 1.5, "empate": 4, "cuotaVisitante": 5.5, "cantidadDeApuestas": 76 },
    { "hora": 11345, "liga": "R-ESCL", "local": "Harrogate Town", "visitante": "Carlisle", "cuotaLocal": 3.3, "empate": 3.4, "cuotaVisitante": 2, "cantidadDeApuestas": 77 },
    { "hora": 11345, "liga": "R-ESCL", "local": "Port Vale", "visitante": "Fleetwood Town", "cuotaLocal": 2.25, "empate": 3.25, "cuotaVisitante": 2.9, "cantidadDeApuestas": 77 },
    { "hora": 11345, "liga": "R-ESCL", "local": "Preston", "visitante": "Salford City", "cuotaLocal": 1.571, "empate": 4, "cuotaVisitante": 5, "cantidadDeApuestas": 75 },
    { "hora": 11345, "liga": "R-ESCL", "local": "Rotherham", "visitante": "Morecambe", "cuotaLocal": 1.48, "empate": 4.2, "cuotaVisitante": 5.75, "cantidadDeApuestas": 76 },
    { "hora": 11345, "liga": "R-ESCL", "local": "Sheffield Wednesday", "visitante": "Stockport County", "cuotaLocal": 1.7, "empate": 3.7, "cuotaVisitante": 4.333, "cantidadDeApuestas": 75 },
    { "hora": 11345, "liga": "R-ESCL", "local": "Stevenage", "visitante": "Watford", "cuotaLocal": 3.45, "empate": 3.3, "cuotaVisitante": 2, "cantidadDeApuestas": 77 },
    { "hora": 11345, "liga": "R-ESCL", "local": "Sutton United", "visitante": "Cambridge United", "cuotaLocal": 2.55, "empate": 3.3, "cuotaVisitante": 2.5, "cantidadDeApuestas": 78 },
    { "hora": 11345, "liga": "R-ESCL", "local": "Sunderland", "visitante": "Crewe Alexandra", "cuotaLocal": 1.4, "empate": 4.5, "cuotaVisitante": 6.5, "cantidadDeApuestas": 76 },
    { "hora": 11400, "liga": "R-ESCL", "local": "Wrexham FC", "visitante": "Wigan", "cuotaLocal": 1.8, "empate": 3.55, "cuotaVisitante": 3.9, "cantidadDeApuestas": 77 },
    { "hora": 11000, "liga": "U-CHAM", "local": "FC Struga Trim Lum", "visitante": "VMFD Zalgiris", "cuotaLocal": 3.4, "empate": 3, "cuotaVisitante": 2.15, "cantidadDeApuestas": 74 },
    { "hora": 11200, "liga": "U-CHAM", "local": "FC Sheriff Tiraspol", "visitante": "Farul Constanta", "cuotaLocal": 1.8, "empate": 3.35, "cuotaVisitante": 4.333, "cantidadDeApuestas": 76 },
    { "hora": 11200, "liga": "U-CHAM", "local": "FC Flora Tallinn", "visitante": "Rakow Czestochowa", "cuotaLocal": 4.75, "empate": 3.55, "cuotaVisitante": 1.65, "cantidadDeApuestas": 75 },
    { "hora": 11200, "liga": "U-CHAM", "local": "Maccabi Haifa", "visitante": "Hamrun Spartans", "cuotaLocal": 1.133, "empate": 7.5, "cuotaVisitante": 13, "cantidadDeApuestas": 76 },
    { "hora": 11300, "liga": "U-CHAM", "local": "Bate Borisov", "visitante": "FK Partizani Tirana", "cuotaLocal": 2.45, "empate": 2.95, "cuotaVisitante": 2.95, "cantidadDeApuestas": 82 },
    { "hora": 11300, "liga": "U-CHAM", "local": "HSK Zrinjski Mostar", "visitante": "FC Urartu", "cuotaLocal": 1.5, "empate": 3.8, "cuotaVisitante": 6.25, "cantidadDeApuestas": 76 },
    { "hora": 11300, "liga": "U-CHAM", "local": "The New Saints FC", "visitante": "BK Hacken", "cuotaLocal": 5.25, "empate": 4.2, "cuotaVisitante": 1.533, "cantidadDeApuestas": 83 },
    { "hora": 11415, "liga": "U-CHAM", "local": "Breidablik", "visitante": "Shamrock Rovers", "cuotaLocal": 2.15, "empate": 3.3, "cuotaVisitante": 3.1, "cantidadDeApuestas": 87 },
    { "hora": 11230, "liga": "U-CONF", "local": "Balzan FC", "visitante": "NK Domzale", "cuotaLocal": 3.1, "empate": 3.55, "cuotaVisitante": 2.05, "cantidadDeApuestas": 78 },
    { "hora": 11600, "liga": "ZA-BRA2", "local": "Tombense MG", "visitante": "CRB Maceio AL", "cuotaLocal": 2.3, "empate": 3.1, "cuotaVisitante": 3.2, "cantidadDeApuestas": 101 },
    { "hora": 11700, "liga": "ZA-BRA2", "local": "Chapecoense SC", "visitante": "Ituano SP", "cuotaLocal": 2.1, "empate": 3.1, "cuotaVisitante": 3.7, "cantidadDeApuestas": 101 },
    { "hora": 11930, "liga": "ZA-BRA2", "local": "Ponte Preta SP", "visitante": "Juventude RS", "cuotaLocal": 2.5, "empate": 3, "cuotaVisitante": 2.95, "cantidadDeApuestas": 101 },
    { "hora": 11800, "liga": "ZA-CHIC", "local": "Universidad de Concepcion", "visitante": "CSD Rangers", "cuotaLocal": 2.15, "empate": 3.2, "cuotaVisitante": 3.1, "cantidadDeApuestas": 42 },
    { "hora": 11900, "liga": "ZA-ECU2", "local": "Imbabura SC", "visitante": "Manta FC", "cuotaLocal": 1.8, "empate": 3.2, "cuotaVisitante": 4.2, "cantidadDeApuestas": 42 },
    { "hora": 11700, "liga": "ZA-SUDA", "local": "America Mineiro MG", "visitante": "Colo Colo", "cuotaLocal": 1.95, "empate": 3.5, "cuotaVisitante": 3.9, "cantidadDeApuestas": 115 },
    { "hora": 11900, "liga": "ZA-SUDA", "local": "Estudiantes de La Plata", "visitante": "Barcelona SC", "cuotaLocal": 1.571, "empate": 4.2, "cuotaVisitante": 6, "cantidadDeApuestas": 112 },
    { "hora": 11930, "liga": "ZA-SUDA", "local": "Universitario de Deportes", "visitante": "Corinthians SP", "cuotaLocal": 2.4, "empate": 3.1, "cuotaVisitante": 3.2, "cantidadDeApuestas": 112 }
]

let PARTIDOS_CON_CUOTA = [
    [11200, 'FC Flora Tallinn', 'Rakow Czestochowa', '0.5', 1.42],
    [11200, 'Maccabi Haifa', 'Hamrun Spartans', '0.5', 1.22],
    [11300, 'Bate Borisov', 'FK Partizani Tirana', '0.5', 1.53],
    [11300, 'HSK Zrinjski Mostar', 'FC Urartu', '0.5', 1.45],
    [11300, 'The New Saints FC', 'BK Hacken', '0.5', 1.28],
    [11415, 'Breidablik', 'Shamrock Rovers', '0.5', 1.42],
    [11230, 'Balzan FC', 'NK Domzale', '0.5', 1.33],
    [11600, 'Tombense MG', 'CRB Maceio AL', '0.5', 1.55],
    [11700, 'Chapecoense SC', 'Ituano SP', '0.5', 1.55],
    [11930, 'Ponte Preta SP', 'Juventude RS', '0.5', 1.57],
    [11800, 'Universidad de Concepcion', 'CSD Rangers', '0.5', 1.45],
    [11900, 'Imbabura SC', 'Manta FC', '0.5', 1.48],
    [11700, 'America Mineiro MG', 'Colo Colo', '0.5', 1.42],
    [11900, 'Estudiantes de La Plata', 'Barcelona SC', '0.5', 1.40],
    [11930, 'Universitario de Deportes', 'Corinthians SP', '0.5', 1.55],
    [11330, 'Hereford United', 'Swindon Town', '0.5', 1.18],
    [11330, 'Stevenage', 'Colchester', '0.5', 1.33],
    [11330, 'Torquay United', 'Plymouth Argyle', '0.5', 1.15],
    [11345, 'Glasgow Rangers', 'Newcastle', '0.5', 1.28],
    [11345, 'Cheltenham Town', 'West Bromwich', '0.5', 1.25],
    [11345, 'Hull City', 'Barnsley', '0.5', 1.35],
    [11345, 'AFC Fylde', 'Barrow FC', '0.5', 1.25],
    [11345, 'Chester FC', 'Stockport County', '0.5', 1.22],
    [11345, 'Sutton United', 'Millwall', '0.5', 1.33],
    [11345, 'Alloa Athletic', 'Stirling Albion', '0.5', 1.28],
    [11345, 'Ayr United', 'Stenhousemuir', '0.5', 1.25],
    [11345, 'Dundee United', 'Partick Thistle', '0.5', 1.28],
    [11345, 'Spartans FC', 'Falkirk', '0.5', 1.28],
    [11345, 'Bonnyrigg Rose', 'Dundee', '0.5', 1.25],
    [11345, 'Cove', 'Clyde', '0.5', 1.25],
    [11345, 'Dumbarton', 'Inverness CT', '0.5', 1.28],
    [11345, 'Dunfermline', 'Annan Athletic', '0.5', 1.25],
    [11345, 'East Fife', 'Elgin City', '0.5', 1.33],
    [11345, 'Greenock Morton', 'Stranraer', '0.5', 1.25],
    [11345, 'Hamilton Academical', 'Brechin City', '0.5', 1.25],
    [11345, 'Montrose', 'Forfar Athletic', '0.5', 1.30],
    [11345, 'Queen of the South', 'Motherwell', '0.5', 1.28],
    [11345, 'Raith Rovers', 'Albion Rovers', '0.5', 1.25],
    [11000, 'FC Struga Trim Lum', 'VMFD Zalgiris', '0.5', 1.57],
    [11200, 'FC Sheriff Tiraspol', 'Farul Constanta', '0.5', 1.53],
    [10500, 'Tottenham', 'West Ham United', '0.5', 1.30],
    [10630, 'Bristol City', 'Swindon Town', '0.5', 1.25],
    [11000, 'Génova', 'WSG Tirol', '0.5', 1.30],
    [11100, 'Austria Wien', 'Aris Limassol', '0.5', 1.25],
    [11200, 'Valencia', 'Nottingham Forest', '0.5', 1.36],
    [11200, 'Real Oviedo', 'Racing Santander', '0.5', 1.42],
    [11200, 'Sturm Graz', 'Galatasaray', '0.5', 1.28],
    [11200, 'FC Penafiel', 'Desportivo Chaves', '0.5', 1.38],
    [11200, 'Sevilla', 'AD Ceuta', '0.5', 1.25],
    [11230, 'Osasuna', 'SD Huesca', '0.5', 1.36],
    [11230, 'Altach', 'Villarreal', '0.5', 1.28],
    [11300, 'Real Murcia', 'Sheffield Wednesday', '0.5', 1.33],
    [11300, 'Panathinaikos', 'Rayo Vallecano', '0.5', 1.40],
    [11300, 'Forest Green Rovers', 'Coventry', '0.5', 1.33],
    [11300, 'FC Lisse', 'SC Telstar', '0.5', 1.22],
    [11300, 'FC Rijnvogels', 'Koninklijke HFC', '0.5', 1.20],
    [11330, 'Brackley Town', 'Burton Albion', '0.5', 1.20],
    [11330, 'Southport FC', 'Morecambe', '0.5', 1.25],
    [11330, 'Swindon Supermarine', 'Chippenham Town', '0.5', 1.25],
    [11330, 'Gillingham', 'Charlton Athletic', '0.5', 1.30],
  ]

  

const retorno = []

for (const partido of PARTIDOS_OPTIMIZADOS) {
    let local = partido.local
    let partido_encontrado = PARTIDOS_CON_CUOTA.find(p => p[1] === local )

    if (partido_encontrado) {
        let partido_retorno = { ...partido, cuotaCualquiera: partido_encontrado[4] }
        retorno.push( partido_retorno )
    } else {
        retorno.push( partido )
    }
}

const fs = require('fs')

fs.writeFileSync('retorno.txt', 'let PARTIDOS_OPTIMIZADOS = ' + JSON.stringify(retorno))