let LIGAS = [
	{"liga":"ZA-ARGC","mitad":true,"mitadFavorito":true,"codigoWplay":19572},
	{"liga":"YE-BIE1","mitad":false,"mitadFavorito":false,"codigoWplay":19493},
	{"liga":"S-CHI1","mitad":false,"mitadFavorito":true,"codigoWplay":19485},
	{"liga":"ZA-COLC","mitad":true,"mitadFavorito":true,"codigoWplay":29698},
	{"liga":"ZA-ECU2","mitad":false,"mitadFavorito":false,"codigoWplay":30530},
	{"liga":"ESP1","mitad":true,"mitadFavorito":true,"codigoWplay":19160},
	{"liga":"R-ING2","mitad":true,"mitadFavorito":true,"codigoWplay":19156},
	{"liga":"ITA2","mitad":true,"mitadFavorito":true,"codigoWplay":19328},
	{"liga":"ZA-MEX1","mitad":true,"mitadFavorito":true,"codigoWplay":19329},
	{"liga":"I-AMI","mitad":true,"mitadFavorito":true,"codigoWplay":19287},
	{"liga":"YE-POR2","mitad":false,"mitadFavorito":true,"codigoWplay":19338},
	{"liga":"YE-REP1","mitad":false,"mitadFavorito":true,"codigoWplay":19403},
	{"liga":"ZA-LIBE","mitad":true,"mitadFavorito":true,"codigoWplay":19462},
	{"liga":"ZA-SUDA","mitad":true,"mitadFavorito":true,"codigoWplay":19348},
	{"liga":"YE-SUI1","mitad":true,"mitadFavorito":true,"codigoWplay":19305},
	{"liga":"YE-TUR2","mitad":false,"mitadFavorito":false,"codigoWplay":19370},
]