let PARTIDOS_OPTIMIZADOS = [
    { "hora": 11300, "liga": "ALE3", "local": "1.FC Saarbrücken", "visitante": "SSV Ulm 1846", "cuotaLocal": 2, "empate": 3.5, "cuotaVisitante": 3.3, "cantidadDeApuestas": 78, "cuotaCualquiera": 1.38, "cuotaFavorito": 1.909, "rate": "1.38", "stake": 0, "favorito": "local" },
    { "hora": 11030, "liga": "YE-RUM1", "local": "FC U Craiova 1948", "visitante": "Petrolul Ploiesti", "cuotaLocal": 2.35, "empate": 3.1, "cuotaVisitante": 2.95, "cantidadDeApuestas": 78, "cuotaCualquiera": 1.444, "cuotaFavorito": 1.95, "rate": "1.35", "stake": 0, "favorito": "local" },
    { "hora": 11330, "liga": "YE-RUM1", "local": "CS Municipal Studentesc Iasi", "visitante": "FCSB", "cuotaLocal": 3.95, "empate": 3.3, "cuotaVisitante": 1.85, "cantidadDeApuestas": 78, "cuotaCualquiera": 1.363, "cuotaFavorito": 1.7, "rate": "1.25", "stake": 0, "favorito": "visitante" },
    { "hora": 11230, "liga": "ALE1", "local": "Werder Bremen", "visitante": "RB Leipzig", "cuotaLocal": 5.5, "empate": 4.5, "cuotaVisitante": 1.571, "cantidadDeApuestas": 249, "cuotaCualquiera": 1.222, "cuotaFavorito": 1.48, "rate": "1.21", "stake": 0, "favorito": "visitante" },
    { "hora": 11430, "liga": "ALE1", "local": "Hoffenheim", "visitante": "SV Darmstadt 98", "cuotaLocal": 1.48, "empate": 5, "cuotaVisitante": 6.25, "cantidadDeApuestas": 240, "cuotaCualquiera": 1.25, "cuotaFavorito": 1.48, "rate": "1.18", "stake": 0, "favorito": "local" },
    { "hora": 11430, "liga": "ALE1", "local": "Borussia Dortmund", "visitante": "Mainz 05", "cuotaLocal": 1.5, "empate": 4.75, "cuotaVisitante": 5.75, "cantidadDeApuestas": 280, "cuotaCualquiera": 1.222, "cuotaFavorito": 1.48, "rate": "1.21", "stake": 0, "favorito": "local" },
    { "hora": 11300, "liga": "ESP1", "local": "Rayo Vallecano", "visitante": "Valencia", "cuotaLocal": 2.2, "empate": 3.2, "cuotaVisitante": 3.6, "cantidadDeApuestas": 277, "cuotaCualquiera": 1.5, "cuotaFavorito": 2.65, "rate": "1.77", "stake": 0, "favorito": "visitante" },
    { "hora": 11530, "liga": "ESP1", "local": "Atlético Madrid", "visitante": "Getafe", "cuotaLocal": 1.444, "empate": 4.5, "cuotaVisitante": 8, "cantidadDeApuestas": 268, "cuotaCualquiera": 1.38, "cuotaFavorito": 1.65, "rate": "1.20", "stake": 0, "favorito": "local" },
    { "hora": 11530, "liga": "ESP1", "local": "Granada", "visitante": "Sevilla", "cuotaLocal": 2.75, "empate": 3.45, "cuotaVisitante": 2.6, "cantidadDeApuestas": 280, "cuotaCualquiera": 1.4, "cuotaFavorito": 2.1, "rate": "1.50", "stake": 0, "favorito": "visitante" },
    { "hora": 11300, "liga": "ESP2", "local": "Albacete Balompie", "visitante": "CD Eldense", "cuotaLocal": 1.615, "empate": 3.7, "cuotaVisitante": 5.5, "cantidadDeApuestas": 113, "cuotaCualquiera": 1.444, "cuotaFavorito": 1.727, "rate": "1.20", "stake": 0, "favorito": "local" },
    { "hora": 11300, "liga": "ESP2", "local": "Racing Santander", "visitante": "Andorra CF", "cuotaLocal": 2.375, "empate": 3.25, "cuotaVisitante": 2.9, "cantidadDeApuestas": 114, "cuotaCualquiera": 1.45, "cuotaFavorito": 2, "rate": "1.38", "stake": 0, "favorito": "local" },
    { "hora": 11530, "liga": "ESP2", "local": "Espanyol", "visitante": "Burgos CF", "cuotaLocal": 1.615, "empate": 3.6, "cuotaVisitante": 5.75, "cantidadDeApuestas": 113, "cuotaCualquiera": 1.45, "cuotaFavorito": 1.7, "rate": "1.17", "stake": 0, "favorito": "local" },
    { "hora": 11530, "liga": "ESP2", "local": "Elche", "visitante": "Mirandes", "cuotaLocal": 1.727, "empate": 3.65, "cuotaVisitante": 4.5, "cantidadDeApuestas": 113, "cuotaCualquiera": 1.4, "cuotaFavorito": 1.7, "rate": "1.21", "stake": 0, "favorito": "local" },
    { "hora": 11445, "liga": "FRA2", "local": "Concarneau", "visitante": "Grenoble", "cuotaLocal": 3.2, "empate": 3.2, "cuotaVisitante": 2.25, "cantidadDeApuestas": 109, "cuotaCualquiera": 1.48, "cuotaFavorito": 2, "rate": "1.35", "stake": 0, "favorito": "visitante" },
    { "hora": 11445, "liga": "FRA2", "local": "Ajaccio", "visitante": "Valenciennes", "cuotaLocal": 1.95, "empate": 3, "cuotaVisitante": 4.5, "cantidadDeApuestas": 107, "cuotaCualquiera": 1.615, "cuotaFavorito": 2.05, "rate": "1.27", "stake": 0, "favorito": "local" },
    { "hora": 11445, "liga": "FRA2", "local": "Dunkerque", "visitante": "Burdeos", "cuotaLocal": 3.55, "empate": 3.4, "cuotaVisitante": 2.05, "cantidadDeApuestas": 111, "cuotaCualquiera": 1.42, "cuotaFavorito": 1.85, "rate": "1.30", "stake": 0, "favorito": "visitante" },
    { "hora": 11445, "liga": "FRA2", "local": "Angers SCO", "visitante": "EA Guingamp", "cuotaLocal": 2.05, "empate": 3.2, "cuotaVisitante": 3.7, "cantidadDeApuestas": 109, "cuotaCualquiera": 1.533, "cuotaFavorito": 2, "rate": "1.30", "stake": 0, "favorito": "local" },
    { "hora": 11445, "liga": "FRA2", "local": "Pau FC", "visitante": "Troyes", "cuotaLocal": 1.95, "empate": 3.45, "cuotaVisitante": 3.7, "cantidadDeApuestas": 111, "cuotaCualquiera": 1.363, "cuotaFavorito": 1.727, "rate": "1.27", "stake": 0, "favorito": "local" },
    { "hora": 11445, "liga": "FRA2", "local": "Paris FC", "visitante": "Quevilly US", "cuotaLocal": 2.25, "empate": 3.2, "cuotaVisitante": 3.2, "cantidadDeApuestas": 110, "cuotaCualquiera": 1.45, "cuotaFavorito": 1.95, "rate": "1.34", "stake": 0, "favorito": "local" },
    { "hora": 11445, "liga": "FRA2", "local": "Saint Etienne", "visitante": "SC Bastia", "cuotaLocal": 1.85, "empate": 3.45, "cuotaVisitante": 4, "cantidadDeApuestas": 111, "cuotaCualquiera": 1.42, "cuotaFavorito": 1.769, "rate": "1.25", "stake": 0, "favorito": "local" },
    { "hora": 11445, "liga": "FRA2", "local": "Annecy FC", "visitante": "Rodez Aveyron", "cuotaLocal": 2.5, "empate": 3.2, "cuotaVisitante": 2.8, "cantidadDeApuestas": 110, "cuotaCualquiera": 1.48, "cuotaFavorito": 2.2, "rate": "1.49", "stake": 0, "favorito": "visitante" },
    { "hora": 11445, "liga": "FRA2", "local": "Laval", "visitante": "AJ Auxerre", "cuotaLocal": 3.25, "empate": 3.25, "cuotaVisitante": 2.2, "cantidadDeApuestas": 109, "cuotaCualquiera": 1.45, "cuotaFavorito": 1.95, "rate": "1.34", "stake": 0, "favorito": "visitante" },
    { "hora": 11445, "liga": "FRA2", "local": "SC Amiens", "visitante": "Caen", "cuotaLocal": 2.375, "empate": 3.1, "cuotaVisitante": 3, "cantidadDeApuestas": 110, "cuotaCualquiera": 1.48, "cuotaFavorito": 2.25, "rate": "1.52", "stake": 0, "favorito": "visitante" },
    { "hora": 11245, "liga": "YE-HOLC", "local": "Quick Boys", "visitante": "De Graafschap", "cuotaLocal": 3.65, "empate": 3.7, "cuotaVisitante": 1.95, "cantidadDeApuestas": 81, "cuotaCualquiera": 1.3, "cuotaFavorito": 1.727, "rate": "1.33", "stake": 0, "favorito": "visitante" },
    { "hora": 11400, "liga": "YE-HOLC", "local": "FC Dordrecht", "visitante": "Cambuur Leeuwarden", "cuotaLocal": 3, "empate": 3.85, "cuotaVisitante": 2.15, "cantidadDeApuestas": 87, "cuotaCualquiera": 1.25, "cuotaFavorito": 1.65, "rate": "1.32", "stake": 0, "favorito": "visitante" },
    { "hora": 11400, "liga": "YE-HOLC", "local": "FC Eindhoven", "visitante": "Fortuna Sittard", "cuotaLocal": 3.65, "empate": 3.7, "cuotaVisitante": 1.95, "cantidadDeApuestas": 86, "cuotaCualquiera": 1.3, "cuotaFavorito": 1.727, "rate": "1.33", "stake": 0, "favorito": "visitante" },
    { "hora": 11400, "liga": "YE-HOLC", "local": "Spakenburg", "visitante": "SBV Excelsior", "cuotaLocal": 5, "empate": 4.333, "cuotaVisitante": 1.6, "cantidadDeApuestas": 76, "cuotaCualquiera": 1.25, "cuotaFavorito": 2.4, "rate": "1.92", "stake": 0, "favorito": "local" },
    { "hora": 11400, "liga": "YE-HOLC", "local": "RKVV DEM", "visitante": "Excelsior Maassluis", "cuotaLocal": 2.85, "empate": 3.45, "cuotaVisitante": 2.375, "cantidadDeApuestas": 82, "cuotaCualquiera": 1.333, "cuotaFavorito": 1.85, "rate": "1.39", "stake": 0, "favorito": "visitante" },
    { "hora": 11500, "liga": "YE-HOLC", "local": "Willem II Tilburg", "visitante": "Groningen", "cuotaLocal": 2.05, "empate": 3.65, "cuotaVisitante": 3.4, "cantidadDeApuestas": 86, "cuotaCualquiera": 1.333, "cuotaFavorito": 1.769, "rate": "1.33", "stake": 0, "favorito": "local" },
    { "hora": 11200, "liga": "YE-TUR1", "local": "Istanbulspor AS", "visitante": "Trabzonspor", "cuotaLocal": 5, "empate": 4, "cuotaVisitante": 1.65, "cantidadDeApuestas": 181, "cuotaCualquiera": 1.3, "cuotaFavorito": 1.615, "rate": "1.24", "stake": 0, "favorito": "visitante" },
    { "hora": 11200, "liga": "YE-TUR1", "local": "Gaziantep BB", "visitante": "Adana Demirspor", "cuotaLocal": 2.8, "empate": 3.6, "cuotaVisitante": 2.375, "cantidadDeApuestas": 184, "cuotaCualquiera": 1.3, "cuotaFavorito": 1.85, "rate": "1.42", "stake": 0, "favorito": "visitante" },
    { "hora": 10600, "liga": "YE-TUR2", "local": "Tuzlaspor", "visitante": "Sakaryaspor", "cuotaLocal": 3.8, "empate": 3.45, "cuotaVisitante": 1.833, "cantidadDeApuestas": 43, "cuotaCualquiera": 1.38, "cuotaFavorito": 1, "rate": 1, "stake": 0 },
    { "hora": 10900, "liga": "YE-TUR2", "local": "Giresunspor", "visitante": "Genclerbirligi", "cuotaLocal": 5, "empate": 3.75, "cuotaVisitante": 1.571, "cantidadDeApuestas": 43, "cuotaCualquiera": 1.4, "cuotaFavorito": 1, "rate": 1, "stake": 0 },
    { "hora": 11200, "liga": "YE-TUR2", "local": "Kocaelispor", "visitante": "Bodrum Belediyesi Bodrumspor", "cuotaLocal": 2.7, "empate": 3.1, "cuotaVisitante": 2.5, "cantidadDeApuestas": 43, "cuotaCualquiera": 1.48, "cuotaFavorito": 1, "rate": 1, "stake": 0 },
    { "hora": 11445, "liga": "R-INGF", "local": "Blackpool", "visitante": "Forest Green Rovers", "cuotaLocal": 1.45, "empate": 4.5, "cuotaVisitante": 6.25, "cantidadDeApuestas": 103, "cuotaCualquiera": 1.285, "cuotaFavorito": 1.45, "rate": "1.13", "stake": 0, "favorito": "local" },
    { "hora": 11445, "liga": "R-INGE", "local": "Port Vale", "visitante": "Middlesbrough", "cuotaLocal": 4, "empate": 4, "cuotaVisitante": 1.85, "cantidadDeApuestas": 188, "cuotaCualquiera": 1.3, "cuotaFavorito": 1.7, "rate": "1.31", "stake": 0, "favorito": "visitante" },
    { "hora": 11445, "liga": "R-INGE", "local": "Everton", "visitante": "Fulham", "cuotaLocal": 2, "empate": 3.8, "cuotaVisitante": 3.6, "cantidadDeApuestas": 188, "cuotaCualquiera": 1.363, "cuotaFavorito": 1.85, "rate": "1.36", "stake": 0, "favorito": "local" },
    { "hora": 11500, "liga": "R-INGE", "local": "Chelsea", "visitante": "Newcastle", "cuotaLocal": 1.9, "empate": 3.85, "cuotaVisitante": 4, "cantidadDeApuestas": 188, "cuotaCualquiera": 1.35, "cuotaFavorito": 2.4, "rate": "1.78", "stake": 0, "favorito": "visitante" },
    { "hora": 11500, "liga": "ITAC", "local": "Napoles", "visitante": "Frosinone", "cuotaLocal": 1.444, "empate": 5, "cuotaVisitante": 7, "cantidadDeApuestas": 189, "cuotaCualquiera": 1.25, "cuotaFavorito": 1.48, "rate": "1.18", "stake": 0, "favorito": "local" },
    { "hora": 11300, "liga": "CF-M", "local": "Urawa Red Diamonds", "visitante": "Manchester City", "cuotaLocal": 15, "empate": 8.5, "cuotaVisitante": 1.166, "cantidadDeApuestas": 175, "cuotaCualquiera": 1.222, "cuotaFavorito": 1.333, "rate": "1.09", "stake": 0, "favorito": "visitante" },
    { "hora": 11300, "liga": "ALE3", "local": "FC Ingolstadt 04", "visitante": "FC Erzgebirge Aue", "cuotaLocal": 1, "empate": 1, "cuotaVisitante": 1, "cantidadDeApuestas": 78, "cuotaCualquiera": 1.333, "cuotaFavorito": 1.769, "rate": "1.33", "stake": 0, "favorito": "local" },
    { "hora": 11300, "liga": "ALE3", "local": "Rot Weiss Essen", "visitante": "Hallescher FC", "cuotaLocal": 1, "empate": 1, "cuotaVisitante": 1, "cantidadDeApuestas": 78, "cuotaCualquiera": 1.3, "cuotaFavorito": 1.666, "rate": "1.28", "stake": 0, "favorito": "local" },
    { "hora": 11300, "liga": "ALE3", "local": "SV Sandhausen", "visitante": "VfB Lübeck", "cuotaLocal": 1, "empate": 1, "cuotaVisitante": 1, "cantidadDeApuestas": 78, "cuotaCualquiera": 1.3, "cuotaFavorito": 1.615, "rate": "1.24", "stake": 0, "favorito": "local" },
    { "hora": 11300, "liga": "ALE3", "local": "SpVgg Unterhaching", "visitante": "Jahn Regensburg", "cuotaLocal": 1, "empate": 1, "cuotaVisitante": 1, "cantidadDeApuestas": 78, "cuotaCualquiera": 1.42, "cuotaFavorito": 2.25, "rate": "1.58", "stake": 0, "favorito": "local" },
    { 
        "hora": 10900,
        "liga": "YE-TUR1",
        "local": 'Istanbul Basaksehir FK',
        "visitante": 'Sivasspor',
        "cuotaLocal": 2.8,
        "empate": 3.6,
        "cuotaVisitante": 2.375,
        "cantidadDeApuestas": 184,
        "cuotaCualquiera": 1.3,
        "cuotaFavorito": 1.95,
        "rate": "1.42",
        "stake": 0,
        "favorito": "local" 
    },
    
    
    
    
        

]
